-- Country/territory seed.
-- Names are stored in English.
-- Airports are intentionally not inserted in this version.

USE icaro_ops;

INSERT INTO countries (
  world_region_code,
  name,
  subregion_name,
  has_airports
) VALUES
('AFRICA', 'Algeria', 'North Africa', 1),
('AFRICA', 'Egypt', 'North Africa', 1),
('AFRICA', 'Libya', 'North Africa', 1),
('AFRICA', 'Morocco', 'North Africa', 1),
('AFRICA', 'Sudan', 'North Africa', 1),
('AFRICA', 'Tunisia', 'North Africa', 1),
('AFRICA', 'Western Sahara', 'North Africa', 1),
('AFRICA', 'British Indian Ocean Territory', 'East Africa', 1),
('AFRICA', 'Burundi', 'East Africa', 1),
('AFRICA', 'Comoros', 'East Africa', 1),
('AFRICA', 'Djibouti', 'East Africa', 1),
('AFRICA', 'Eritrea', 'East Africa', 1),
('AFRICA', 'Ethiopia', 'East Africa', 1),
('AFRICA', 'Kenya', 'East Africa', 1),
('AFRICA', 'Madagascar', 'East Africa', 1),
('AFRICA', 'Malawi', 'East Africa', 1),
('AFRICA', 'Mauritius', 'East Africa', 1),
('AFRICA', 'Mayotte', 'East Africa', 1),
('AFRICA', 'Mozambique', 'East Africa', 1),
('AFRICA', 'Réunion', 'East Africa', 1),
('AFRICA', 'Rwanda', 'East Africa', 1),
('AFRICA', 'Seychelles', 'East Africa', 1),
('AFRICA', 'Somalia', 'East Africa', 1),
('AFRICA', 'South Sudan', 'East Africa', 1),
('AFRICA', 'Tanzania', 'East Africa', 1),
('AFRICA', 'Uganda', 'East Africa', 1),
('AFRICA', 'Zambia', 'East Africa', 1),
('AFRICA', 'Zimbabwe', 'East Africa', 1),
('AFRICA', 'Angola', 'Central Africa', 1),
('AFRICA', 'Cameroon', 'Central Africa', 1),
('AFRICA', 'Central African Republic', 'Central Africa', 1),
('AFRICA', 'Chad', 'Central Africa', 1),
('AFRICA', 'Democratic Republic of the Congo', 'Central Africa', 1),
('AFRICA', 'Republic of the Congo', 'Central Africa', 1),
('AFRICA', 'Equatorial Guinea', 'Central Africa', 1),
('AFRICA', 'Gabon', 'Central Africa', 1),
('AFRICA', 'São Tomé and Príncipe', 'Central Africa', 1),
('AFRICA', 'Botswana', 'Southern Africa', 1),
('AFRICA', 'Eswatini', 'Southern Africa', 1),
('AFRICA', 'Lesotho', 'Southern Africa', 1),
('AFRICA', 'Namibia', 'Southern Africa', 1),
('AFRICA', 'South Africa', 'Southern Africa', 1),
('AFRICA', 'Benin', 'Western Africa', 1),
('AFRICA', 'Burkina Faso', 'Western Africa', 1),
('AFRICA', 'Cabo Verde', 'Western Africa', 1),
('AFRICA', 'Côte d''Ivoire', 'Western Africa', 1),
('AFRICA', 'The Gambia', 'Western Africa', 1),
('AFRICA', 'Ghana', 'Western Africa', 1),
('AFRICA', 'Guinea', 'Western Africa', 1),
('AFRICA', 'Guinea-Bissau', 'Western Africa', 1),
('AFRICA', 'Liberia', 'Western Africa', 1),
('AFRICA', 'Mali', 'Western Africa', 1),
('AFRICA', 'Mauritania', 'Western Africa', 1),
('AFRICA', 'Niger', 'Western Africa', 1),
('AFRICA', 'Nigeria', 'Western Africa', 1),
('AFRICA', 'Saint Helena, Ascension and Tristan da Cunha', 'Western Africa', 1),
('AFRICA', 'Senegal', 'Western Africa', 1),
('AFRICA', 'Sierra Leone', 'Western Africa', 1),
('AFRICA', 'Togo', 'Western Africa', 1),
('ANTARCTICA', 'Antarctica', NULL, 1),
('ASIA', 'Abkhazia', 'Western Asia', 1),
('ASIA', 'Armenia', 'Western Asia', 1),
('ASIA', 'Republic of Artsakh', 'Western Asia', 1),
('ASIA', 'Azerbaijan', 'Western Asia', 1),
('ASIA', 'Bahrain', 'Western Asia', 1),
('ASIA', 'Northern Cyprus', 'Western Asia', 1),
('ASIA', 'Georgia', 'Western Asia', 1),
('ASIA', 'Iraq', 'Western Asia', 1),
('ASIA', 'Israel', 'Western Asia', 1),
('ASIA', 'Jordan', 'Western Asia', 1),
('ASIA', 'Kuwait', 'Western Asia', 1),
('ASIA', 'Lebanon', 'Western Asia', 1),
('ASIA', 'Oman', 'Western Asia', 1),
('ASIA', 'State of Palestine', 'Western Asia', 1),
('ASIA', 'Qatar', 'Western Asia', 1),
('ASIA', 'Russia', 'Western Asia', 1),
('ASIA', 'Saudi Arabia', 'Western Asia', 1),
('ASIA', 'Syria', 'Western Asia', 1),
('ASIA', 'Turkey', 'Western Asia', 1),
('ASIA', 'United Arab Emirates', 'Western Asia', 1),
('ASIA', 'Yemen', 'Western Asia', 1),
('ASIA', 'Kazakhstan', 'Central Asia', 1),
('ASIA', 'Kyrgyzstan', 'Central Asia', 1),
('ASIA', 'Tajikistan', 'Central Asia', 1),
('ASIA', 'Turkmenistan', 'Central Asia', 1),
('ASIA', 'Uzbekistan', 'Central Asia', 1),
('ASIA', 'Afghanistan', 'Southern Asia', 1),
('ASIA', 'Bangladesh', 'Southern Asia', 1),
('ASIA', 'Bhutan', 'Southern Asia', 1),
('ASIA', 'British Indian Ocean Territory', 'Southern Asia', 1),
('ASIA', 'India', 'Southern Asia', 1),
('ASIA', 'Iran', 'Southern Asia', 1),
('ASIA', 'Maldives', 'Southern Asia', 1),
('ASIA', 'Nepal', 'Southern Asia', 1),
('ASIA', 'Pakistan', 'Southern Asia', 1),
('ASIA', 'Sri Lanka', 'Southern Asia', 1),
('ASIA', 'China', 'Eastern Asia', 1),
('ASIA', 'Hong Kong', 'Eastern Asia', 1),
('ASIA', 'Japan', 'Eastern Asia', 1),
('ASIA', 'Macau', 'Eastern Asia', 1),
('ASIA', 'Mongolia', 'Eastern Asia', 1),
('ASIA', 'North Korea', 'Eastern Asia', 1),
('ASIA', 'South Korea', 'Eastern Asia', 1),
('ASIA', 'Taiwan', 'Eastern Asia', 1),
('ASIA', 'Brunei', 'Southeastern Asia', 1),
('ASIA', 'Cambodia', 'Southeastern Asia', 1),
('ASIA', 'Indonesia', 'Southeastern Asia', 1),
('ASIA', 'Laos', 'Southeastern Asia', 1),
('ASIA', 'Malaysia', 'Southeastern Asia', 1),
('ASIA', 'Myanmar', 'Southeastern Asia', 1),
('ASIA', 'Philippines', 'Southeastern Asia', 1),
('ASIA', 'Singapore', 'Southeastern Asia', 1),
('ASIA', 'Thailand', 'Southeastern Asia', 1),
('ASIA', 'Timor-Leste', 'Southeastern Asia', 1),
('ASIA', 'Vietnam', 'Southeastern Asia', 1),
('EUROPE', 'Armenia', 'Eastern Europe', 1),
('EUROPE', 'Azerbaijan', 'Eastern Europe', 1),
('EUROPE', 'Belarus', 'Eastern Europe', 1),
('EUROPE', 'Bulgaria', 'Eastern Europe', 1),
('EUROPE', 'Czech Republic', 'Eastern Europe', 1),
('EUROPE', 'Georgia', 'Eastern Europe', 1),
('EUROPE', 'Hungary', 'Eastern Europe', 1),
('EUROPE', 'Poland', 'Eastern Europe', 1),
('EUROPE', 'Republic of Moldova', 'Eastern Europe', 1),
('EUROPE', 'Romania', 'Eastern Europe', 1),
('EUROPE', 'Russian Federation', 'Eastern Europe', 1),
('EUROPE', 'Slovakia', 'Eastern Europe', 1),
('EUROPE', 'Ukraine', 'Eastern Europe', 1),
('EUROPE', 'Denmark', 'Northern Europe', 1),
('EUROPE', 'Estonia', 'Northern Europe', 1),
('EUROPE', 'Finland', 'Northern Europe', 1),
('EUROPE', 'Iceland', 'Northern Europe', 1),
('EUROPE', 'Ireland', 'Northern Europe', 1),
('EUROPE', 'Latvia', 'Northern Europe', 1),
('EUROPE', 'Lithuania', 'Northern Europe', 1),
('EUROPE', 'Norway', 'Northern Europe', 1),
('EUROPE', 'Sweden', 'Northern Europe', 1),
('EUROPE', 'United Kingdom', 'Northern Europe', 1),
('EUROPE', 'Albania', 'Southern Europe', 1),
('EUROPE', 'Bosnia and Herzegovina', 'Southern Europe', 1),
('EUROPE', 'Croatia', 'Southern Europe', 1),
('EUROPE', 'Cyprus', 'Southern Europe', 1),
('EUROPE', 'Gibraltar', 'Southern Europe', 1),
('EUROPE', 'Greece', 'Southern Europe', 1),
('EUROPE', 'Italy', 'Southern Europe', 1),
('EUROPE', 'Malta', 'Southern Europe', 1),
('EUROPE', 'Montenegro', 'Southern Europe', 1),
('EUROPE', 'North Macedonia', 'Southern Europe', 1),
('EUROPE', 'Portugal', 'Southern Europe', 1),
('EUROPE', 'Serbia', 'Southern Europe', 1),
('EUROPE', 'Slovenia', 'Southern Europe', 1),
('EUROPE', 'Spain', 'Southern Europe', 1),
('EUROPE', 'Turkey', 'Southern Europe', 1),
('EUROPE', 'Austria', 'Western Europe', 1),
('EUROPE', 'Belgium', 'Western Europe', 1),
('EUROPE', 'France', 'Western Europe', 1),
('EUROPE', 'Germany', 'Western Europe', 1),
('EUROPE', 'Luxembourg', 'Western Europe', 1),
('EUROPE', 'Netherlands', 'Western Europe', 1),
('EUROPE', 'Switzerland', 'Western Europe', 1),
('EUROPE', 'Andorra', 'Countries without fixed-wing airports', 0),
('EUROPE', 'Liechtenstein', 'Countries without fixed-wing airports', 0),
('EUROPE', 'Monaco', 'Countries without fixed-wing airports', 0),
('EUROPE', 'San Marino', 'Countries without fixed-wing airports', 0),
('EUROPE', 'Vatican City', 'Countries without fixed-wing airports', 0),
('NORTH_AMERICA', 'United States', 'Northern America', 1),
('NORTH_AMERICA', 'Bermuda', 'Northern America', 1),
('NORTH_AMERICA', 'Canada', 'Northern America', 1),
('NORTH_AMERICA', 'Greenland', 'Northern America', 1),
('NORTH_AMERICA', 'Saint Pierre and Miquelon', 'Northern America', 1),
('NORTH_AMERICA', 'Belize', 'Central America', 1),
('NORTH_AMERICA', 'Costa Rica', 'Central America', 1),
('NORTH_AMERICA', 'El Salvador', 'Central America', 1),
('NORTH_AMERICA', 'Guatemala', 'Central America', 1),
('NORTH_AMERICA', 'Honduras', 'Central America', 1),
('NORTH_AMERICA', 'Mexico', 'Central America', 1),
('NORTH_AMERICA', 'Nicaragua', 'Central America', 1),
('NORTH_AMERICA', 'Panama', 'Central America', 1),
('NORTH_AMERICA', 'Anguilla', 'Caribbean', 1),
('NORTH_AMERICA', 'Antigua and Barbuda', 'Caribbean', 1),
('NORTH_AMERICA', 'Aruba', 'Caribbean', 1),
('NORTH_AMERICA', 'Bahamas', 'Caribbean', 1),
('NORTH_AMERICA', 'Barbados', 'Caribbean', 1),
('NORTH_AMERICA', 'British Virgin Islands', 'Caribbean', 1),
('NORTH_AMERICA', 'Cayman Islands', 'Caribbean', 1),
('NORTH_AMERICA', 'Cuba', 'Caribbean', 1),
('NORTH_AMERICA', 'Curaçao', 'Caribbean', 1),
('NORTH_AMERICA', 'Dominica', 'Caribbean', 1),
('NORTH_AMERICA', 'Dominican Republic', 'Caribbean', 1),
('NORTH_AMERICA', 'Grenada', 'Caribbean', 1),
('NORTH_AMERICA', 'Guadeloupe', 'Caribbean', 1),
('NORTH_AMERICA', 'Haiti', 'Caribbean', 1),
('NORTH_AMERICA', 'Jamaica', 'Caribbean', 1),
('NORTH_AMERICA', 'Martinique', 'Caribbean', 1),
('NORTH_AMERICA', 'Montserrat', 'Caribbean', 1),
('NORTH_AMERICA', 'Puerto Rico', 'Caribbean', 1),
('NORTH_AMERICA', 'Saint Barthélemy', 'Caribbean', 1),
('NORTH_AMERICA', 'Saint Kitts and Nevis', 'Caribbean', 1),
('NORTH_AMERICA', 'Saint Lucia', 'Caribbean', 1),
('NORTH_AMERICA', 'Saint Vincent and the Grenadines', 'Caribbean', 1),
('NORTH_AMERICA', 'Sint Maarten', 'Caribbean', 1),
('NORTH_AMERICA', 'Trinidad and Tobago', 'Caribbean', 1),
('NORTH_AMERICA', 'Turks and Caicos Islands', 'Caribbean', 1),
('NORTH_AMERICA', 'United States Virgin Islands', 'Caribbean', 1),
('OCEANIA', 'Australia', 'Australia and New Zealand', 1),
('OCEANIA', 'Christmas Island', 'Australia and New Zealand', 1),
('OCEANIA', 'Cocos (Keeling) Islands', 'Australia and New Zealand', 1),
('OCEANIA', 'New Zealand', 'Australia and New Zealand', 1),
('OCEANIA', 'Norfolk Island', 'Australia and New Zealand', 1),
('OCEANIA', 'Fiji', 'Melanesia', 1),
('OCEANIA', 'New Caledonia', 'Melanesia', 1),
('OCEANIA', 'Papua New Guinea', 'Melanesia', 1),
('OCEANIA', 'Solomon Islands', 'Melanesia', 1),
('OCEANIA', 'Vanuatu', 'Melanesia', 1),
('OCEANIA', 'Guam', 'Micronesia', 1),
('OCEANIA', 'Kiribati', 'Micronesia', 1),
('OCEANIA', 'Marshall Islands', 'Micronesia', 1),
('OCEANIA', 'Federated States of Micronesia', 'Micronesia', 1),
('OCEANIA', 'Nauru', 'Micronesia', 1),
('OCEANIA', 'Northern Mariana Islands', 'Micronesia', 1),
('OCEANIA', 'Palau', 'Micronesia', 1),
('OCEANIA', 'United States Minor Outlying Islands', 'Micronesia', 1),
('OCEANIA', 'American Samoa', 'Polynesia', 1),
('OCEANIA', 'Cook Islands', 'Polynesia', 1),
('OCEANIA', 'French Polynesia', 'Polynesia', 1),
('OCEANIA', 'Niue', 'Polynesia', 1),
('OCEANIA', 'Samoa', 'Polynesia', 1),
('OCEANIA', 'Tonga', 'Polynesia', 1),
('OCEANIA', 'Tuvalu', 'Polynesia', 1),
('OCEANIA', 'Wallis and Futuna', 'Polynesia', 1),
('SOUTH_AMERICA', 'Argentina', NULL, 1),
('SOUTH_AMERICA', 'Bolivia', NULL, 1),
('SOUTH_AMERICA', 'Brazil', NULL, 1),
('SOUTH_AMERICA', 'Chile', NULL, 1),
('SOUTH_AMERICA', 'Colombia', NULL, 1),
('SOUTH_AMERICA', 'Ecuador', NULL, 1),
('SOUTH_AMERICA', 'Falkland Islands', NULL, 1),
('SOUTH_AMERICA', 'French Guiana', NULL, 1),
('SOUTH_AMERICA', 'Guyana', NULL, 1),
('SOUTH_AMERICA', 'Paraguay', NULL, 1),
('SOUTH_AMERICA', 'Peru', NULL, 1),
('SOUTH_AMERICA', 'Suriname', NULL, 1),
('SOUTH_AMERICA', 'Uruguay', NULL, 1),
('SOUTH_AMERICA', 'Venezuela', NULL, 1)
ON DUPLICATE KEY UPDATE
  subregion_name = VALUES(subregion_name),
  has_airports = VALUES(has_airports),
  is_active = TRUE;
