-- East Africa / Indian Ocean airport seed batch.
-- Countries in this patch:
-- Burundi, Djibouti, Eritrea, British Indian Ocean Territory, Comoros.
-- Rows without ICAO are intentionally skipped because airports.icao_code is the primary key.

USE icaro_ops;

INSERT INTO airports (
  icao_code,
  country_id,
  icao_prefix,
  iata_code,
  name,
  city,
  location_name,
  subdivision_name,
  latitude,
  longitude,
  elevation_ft,
  airport_type,
  service_category,
  is_civilian,
  is_commercial,
  is_military,
  is_closed,
  operator_country_name,
  aip_url,
  chart_url,
  source_rating_percent,
  data_source_name,
  data_source_url,
  data_quality
) VALUES
('HBBA', (SELECT id FROM countries WHERE name = 'Burundi' AND world_region_code = 'AFRICA'), 'HB', 'BJM', 'Melchior Ndadaye International Airport', 'Bujumbura', NULL, 'Bujumbura Mairie', -3.3239444, 29.3185, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burundi', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burundi', 'PARTIAL'),
('HBBE', (SELECT id FROM countries WHERE name = 'Burundi' AND world_region_code = 'AFRICA'), 'HB', 'GID', 'Gitega Airport', 'Gitega', NULL, 'Gitega', -3.4174722, 29.9119722, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burundi', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burundi', 'PARTIAL'),
('HBBL', (SELECT id FROM countries WHERE name = 'Burundi' AND world_region_code = 'AFRICA'), 'HB', NULL, 'Nyanza-Lac Airport - Closed', 'Nyanza-Lac', NULL, 'Makamba', -4.3391389, 29.6006944, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burundi', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burundi', 'PARTIAL'),
('HBBO', (SELECT id FROM countries WHERE name = 'Burundi' AND world_region_code = 'AFRICA'), 'HB', 'KRE', 'Kirundo Airport', 'Kirundo', NULL, 'Kirundo', -2.5446944, 30.0947222, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burundi', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burundi', 'PARTIAL'),
('HDAS', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', 'AII', 'Ali-Sabieh Airport', 'Ali-Sabieh', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDAG', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', NULL, 'Assa-Gueyla Airport', 'Assa-Gueyla', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDCH', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', NULL, 'Chabelley Airport', 'Chabelley', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDDK', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', NULL, 'Dikhil Airport', 'Dikhil', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDAM', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', 'JIB', 'Djibouti–Ambouli International Airport', 'Djibouti City', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDHE', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', NULL, 'Herkale Airport', 'Khôr ‘Angar', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDMO', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', 'MHI', 'Moucha Airport', 'Moucha Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDOB', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', 'OBC', 'Obock Airport', 'Obock', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HDTJ', (SELECT id FROM countries WHERE name = 'Djibouti' AND world_region_code = 'AFRICA'), 'HD', 'TDJ', 'Tadjoura Airport', 'Tadjoura', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Djibouti', 'https://en.wikipedia.org/wiki/List_of_airports_in_Djibouti', 'PARTIAL'),
('HHAG', (SELECT id FROM countries WHERE name = 'Eritrea' AND world_region_code = 'AFRICA'), 'HH', NULL, 'Agordat Airport', 'Agordat', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Eritrea', 'https://en.wikipedia.org/wiki/List_of_airports_in_Eritrea', 'PARTIAL'),
('HHAS', (SELECT id FROM countries WHERE name = 'Eritrea' AND world_region_code = 'AFRICA'), 'HH', 'ASM', 'Asmara International Airport', 'Asmara', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Eritrea', 'https://en.wikipedia.org/wiki/List_of_airports_in_Eritrea', 'PARTIAL'),
('HHSB', (SELECT id FROM countries WHERE name = 'Eritrea' AND world_region_code = 'AFRICA'), 'HH', 'ASA', 'Assab International Airport', 'Assab', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Eritrea', 'https://en.wikipedia.org/wiki/List_of_airports_in_Eritrea', 'PARTIAL'),
('HHMS', (SELECT id FROM countries WHERE name = 'Eritrea' AND world_region_code = 'AFRICA'), 'HH', 'MSW', 'Massawa International Airport', 'Massawa', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Eritrea', 'https://en.wikipedia.org/wiki/List_of_airports_in_Eritrea', 'PARTIAL'),
('HHTS', (SELECT id FROM countries WHERE name = 'Eritrea' AND world_region_code = 'AFRICA'), 'HH', 'TES', 'Teseney Airport', 'Teseney', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Eritrea', 'https://en.wikipedia.org/wiki/List_of_airports_in_Eritrea', 'PARTIAL'),
('HHNF', (SELECT id FROM countries WHERE name = 'Eritrea' AND world_region_code = 'AFRICA'), 'HH', NULL, 'Nakfa Airport', 'Nakfa, Eritrea', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Eritrea', 'https://en.wikipedia.org/wiki/List_of_airports_in_Eritrea', 'PARTIAL'),
('FJDG', (SELECT id FROM countries WHERE name = 'British Indian Ocean Territory' AND world_region_code = 'AFRICA'), 'FJ', NULL, 'Naval Support Facility Diego Garcia', 'Diego Garcia', NULL, NULL, NULL, NULL, NULL, 'AIRFIELD', 'MILITARY', TRUE, FALSE, TRUE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in British Indian Ocean Territory', 'https://en.wikipedia.org/wiki/List_of_airports_in_British_Indian_Ocean_Territory', 'PARTIAL'),
('FMCV', (SELECT id FROM countries WHERE name = 'Comoros' AND world_region_code = 'AFRICA'), 'FM', 'AJN', 'Ouani Airport', 'Anjouan', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Comoros', 'https://en.wikipedia.org/wiki/List_of_airports_in_Comoros', 'PARTIAL'),
('FMCI', (SELECT id FROM countries WHERE name = 'Comoros' AND world_region_code = 'AFRICA'), 'FM', 'NWA', 'Mohéli Bandar Es Eslam Airport', 'Mohéli', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Comoros', 'https://en.wikipedia.org/wiki/List_of_airports_in_Comoros', 'PARTIAL'),
('FMCN', (SELECT id FROM countries WHERE name = 'Comoros' AND world_region_code = 'AFRICA'), 'FM', 'YVA', 'Iconi Airport - closed', 'Moroni', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Comoros', 'https://en.wikipedia.org/wiki/List_of_airports_in_Comoros', 'PARTIAL'),
('FMCH', (SELECT id FROM countries WHERE name = 'Comoros' AND world_region_code = 'AFRICA'), 'FM', 'HAH', 'Prince Said Ibrahim International Airport', 'Moroni', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Comoros', 'https://en.wikipedia.org/wiki/List_of_airports_in_Comoros', 'PARTIAL')
ON DUPLICATE KEY UPDATE
  country_id = VALUES(country_id),
  icao_prefix = VALUES(icao_prefix),
  iata_code = VALUES(iata_code),
  name = VALUES(name),
  city = VALUES(city),
  location_name = VALUES(location_name),
  subdivision_name = VALUES(subdivision_name),
  latitude = VALUES(latitude),
  longitude = VALUES(longitude),
  elevation_ft = VALUES(elevation_ft),
  airport_type = VALUES(airport_type),
  service_category = VALUES(service_category),
  is_civilian = VALUES(is_civilian),
  is_commercial = VALUES(is_commercial),
  is_military = VALUES(is_military),
  is_closed = VALUES(is_closed),
  operator_country_name = VALUES(operator_country_name),
  aip_url = VALUES(aip_url),
  chart_url = VALUES(chart_url),
  source_rating_percent = VALUES(source_rating_percent),
  data_source_name = VALUES(data_source_name),
  data_source_url = VALUES(data_source_url),
  data_quality = VALUES(data_quality);
