-- Réunion, Rwanda and Seychelles airport seed batch.
-- Rows without ICAO are intentionally skipped because airports.icao_code is the primary key.

USE icaro_ops;

INSERT INTO airports (
  icao_code,
  country_id,
  icao_prefix,
  iata_code,
  name,
  city,
  location_name,
  subdivision_name,
  latitude,
  longitude,
  elevation_ft,
  airport_type,
  service_category,
  is_civilian,
  is_commercial,
  is_military,
  is_closed,
  operator_country_name,
  aip_url,
  chart_url,
  source_rating_percent,
  data_source_name,
  data_source_url,
  data_quality
) VALUES
('FMEE', (SELECT id FROM countries WHERE name = 'Réunion' AND world_region_code = 'AFRICA'), 'FME', 'RUN', 'Roland Garros Airport (Gillot Airport)', 'Saint-Denis / Gillot', 'Public', NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Réunion', 'https://en.wikipedia.org/wiki/List_of_airports_in_Réunion', 'PARTIAL'),
('FMEP', (SELECT id FROM countries WHERE name = 'Réunion' AND world_region_code = 'AFRICA'), 'FME', 'ZSE', 'Pierrefonds Airport', 'Saint-Pierre / Pierrefonds', 'Public', NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Réunion', 'https://en.wikipedia.org/wiki/List_of_airports_in_Réunion', 'PARTIAL'),
('HRYI', (SELECT id FROM countries WHERE name = 'Rwanda' AND world_region_code = 'AFRICA'), 'HR', 'BTQ', 'Butare Airport', 'Butare', NULL, 'Southern Province', -2.595, 29.74, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Rwanda', 'https://en.wikipedia.org/wiki/List_of_airports_in_Rwanda', 'PARTIAL'),
('HRZA', (SELECT id FROM countries WHERE name = 'Rwanda' AND world_region_code = 'AFRICA'), 'HR', 'KME', 'Kamembe International Airport', 'Cyangugu', NULL, 'Western Province', -2.4622222, 28.9080556, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Rwanda', 'https://en.wikipedia.org/wiki/List_of_airports_in_Rwanda', 'PARTIAL'),
('HRYG', (SELECT id FROM countries WHERE name = 'Rwanda' AND world_region_code = 'AFRICA'), 'HR', 'GYI', 'Gisenyi Airport', 'Gisenyi', NULL, 'Western Province', -1.6772222, 29.2588889, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Rwanda', 'https://en.wikipedia.org/wiki/List_of_airports_in_Rwanda', 'PARTIAL'),
('HRYR', (SELECT id FROM countries WHERE name = 'Rwanda' AND world_region_code = 'AFRICA'), 'HR', 'KGL', 'Kigali International Airport (Formerly "Gregoire Kayibanda Airport")', 'Kigali', NULL, 'City of Kigali', -1.9686111, 30.1394444, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Rwanda', 'https://en.wikipedia.org/wiki/List_of_airports_in_Rwanda', 'PARTIAL'),
('HRYN', (SELECT id FROM countries WHERE name = 'Rwanda' AND world_region_code = 'AFRICA'), 'HR', NULL, 'Nemba Airport', 'Nemba', NULL, 'Eastern Province', -2.33, 30.2, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Rwanda', 'https://en.wikipedia.org/wiki/List_of_airports_in_Rwanda', 'PARTIAL'),
('HRYU', (SELECT id FROM countries WHERE name = 'Rwanda' AND world_region_code = 'AFRICA'), 'HR', 'RHG', 'Ruhengeri Airport', 'Ruhengeri', NULL, 'Northern Province', -1.5, 29.6336111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Rwanda', 'https://en.wikipedia.org/wiki/List_of_airports_in_Rwanda', 'PARTIAL'),
('FSAL', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Alphonse Airport', 'Alphonse Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSAS', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Assumption Island Airport', 'Assumption Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSSA', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Astove Island Airport', 'Astove Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSSB', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', 'BDI', 'Bird Island Airport', 'Bird Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSSC', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Coëtivy Airport', 'Coëtivy Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSDA', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'D''Arros Island Airport', 'D''Arros Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSSD', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', 'DEI', 'Denis Island Airport', 'Denis Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSDR', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', 'DES', 'Desroches Airport', 'Desroches Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSFA', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Farquhar Airport', 'Farquhar Islands', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSSF', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', 'FRK', 'Frégate Island Airport', 'Frégate Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSIA', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', 'SEZ', 'Seychelles International Airport', 'Mahé Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSMA', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Marie Louise Island Airport', 'Marie Louise Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSPL', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Platte Island Airport', 'Platte Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSPP', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', 'PRI', 'Praslin Island Airport', 'Praslin Island', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL'),
('FSSR', (SELECT id FROM countries WHERE name = 'Seychelles' AND world_region_code = 'AFRICA'), 'FS', NULL, 'Remire Island Airport', 'Remire Island (Eagle Island)', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Seychelles', 'https://en.wikipedia.org/wiki/List_of_airports_in_Seychelles', 'PARTIAL')
ON DUPLICATE KEY UPDATE
  country_id = VALUES(country_id),
  icao_prefix = VALUES(icao_prefix),
  iata_code = VALUES(iata_code),
  name = VALUES(name),
  city = VALUES(city),
  location_name = VALUES(location_name),
  subdivision_name = VALUES(subdivision_name),
  latitude = VALUES(latitude),
  longitude = VALUES(longitude),
  elevation_ft = VALUES(elevation_ft),
  airport_type = VALUES(airport_type),
  service_category = VALUES(service_category),
  is_civilian = VALUES(is_civilian),
  is_commercial = VALUES(is_commercial),
  is_military = VALUES(is_military),
  is_closed = VALUES(is_closed),
  operator_country_name = VALUES(operator_country_name),
  aip_url = VALUES(aip_url),
  chart_url = VALUES(chart_url),
  source_rating_percent = VALUES(source_rating_percent),
  data_source_name = VALUES(data_source_name),
  data_source_url = VALUES(data_source_url),
  data_quality = VALUES(data_quality);
