-- Runway source notes for Tanzania and Uganda.

USE icaro_ops;

INSERT INTO airport_runway_source_notes (
  airport_icao_code,
  source_note,
  data_source_name
) VALUES
('HTAR', 'Runway: 1820 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTBU', 'Runway: 1325 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTDA', 'Runway: 3000 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTDO', 'Runway: 2500 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTGE', 'Runway: 3000 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTKJ', 'Runway: 3600 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTSY', 'Runway: 2000 m', 'Wikipedia - List of airports in Tanzania'),
('HTKI', 'Runway: 1800 m', 'Wikipedia - List of airports in Tanzania'),
('HTLM', 'Runway: 1220 m', 'Wikipedia - List of airports in Tanzania'),
('HTLI', 'Runway: 1748 m', 'Wikipedia - List of airports in Tanzania'),
('HTMA', 'Runway: 1500 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTMI', 'Runway: 1275 m', 'Wikipedia - List of airports in Tanzania'),
('HTMB', 'Runway: 1569 m', 'Wikipedia - List of airports in Tanzania'),
('HTGW', 'Runway: 3330 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTMS', 'Runway: 1569 m', 'Wikipedia - List of airports in Tanzania'),
('HTMP', 'Runway: 1820 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTMT', 'Runway: 2260 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTMU', 'Runway: 1600 m', 'Wikipedia - List of airports in Tanzania'),
('HTMD', 'Runway: 1400 m, Gravel', 'Wikipedia - List of airports in Tanzania'),
('HTMW', 'Runway: 3010 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTNA', 'Runway: 1795 m', 'Wikipedia - List of airports in Tanzania'),
('HTIR', 'Runway: 1670 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTNR', 'Runway: 1445 m', 'Wikipedia - List of airports in Tanzania'),
('HTNJ', 'Runway: 1890 m, Grass', 'Wikipedia - List of airports in Tanzania'),
('HTSO', 'Runway: 1617 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTSU', 'Runway: 1428 m', 'Wikipedia - List of airports in Tanzania'),
('HTTB', 'Runway: 1900 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTTG', 'Runway: 1255 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTKA', 'Runway: 1794 m, Asphalt', 'Wikipedia - List of airports in Tanzania'),
('HTPE', 'Runway: 1517 m', 'Wikipedia - List of airports in Tanzania'),
('HTZA', 'Runway: 3007 m', 'Wikipedia - List of airports in Tanzania'),
('HTLD', 'Runway: 1535 m; operated by TAA', 'Wikipedia - List of airports in Tanzania'),
('HTMK', 'Runway: 1330 m; operated by TANAPA', 'Wikipedia - List of airports in Tanzania'),
('HTMO', 'Runway: 1285 m; operated by TAA', 'Wikipedia - List of airports in Tanzania'),
('HTMG', 'Runway: 1000 m; operated by TAA', 'Wikipedia - List of airports in Tanzania'),
('HTWK', 'Runway: 1244 m; operated by TAA', 'Wikipedia - List of airports in Tanzania'),
('HTMR', 'Runway: 1288 m; operated by TANAPA', 'Wikipedia - List of airports in Tanzania'),
('HTSE', 'Runway: 750 m; operated by TAA', 'Wikipedia - List of airports in Tanzania'),
('HTSN', 'Runway: 1570 m; operated by TANAPA', 'Wikipedia - List of airports in Tanzania'),
('HTSD', 'Runway: 1057 m; operated by TAA', 'Wikipedia - List of airports in Tanzania'),
('HUAJ', 'Runway: 1,131 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUAR', 'Runway: 1,707 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUGG', 'Runway: 1,540 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUBU', 'Runway: 965 m; Grass', 'Wikipedia - List of airports in Uganda'),
('HUEN', 'Runways: 3,658 m and 2,408 m; Asphalt', 'Wikipedia - List of airports in Uganda'),
('HUFP', 'Runway: 850 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUGU', 'Runway: 3,144 m; Asphalt', 'Wikipedia - List of airports in Uganda'),
('HUJI', 'Runway: 1,800 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUKB', 'Runway: 2,408 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUKJ', 'Runway: 1,100 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUKK', 'Runway: 1,278 m; Asphalt', 'Wikipedia - List of airports in Uganda'),
('HULA', 'Surface: Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUKS', 'Runway: 1,570 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUKD', 'Runway: 1,280 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUKI', 'Runway: 1,300 m; Asphalt', 'Wikipedia - List of airports in Uganda'),
('HUKT', 'Runway: 1,900 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUKO', 'Runway: 1,600 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HULI', 'Runway: 846 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUMI', 'Runway: 2,042 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUMA', 'Runway: 1,635 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUMO', 'Runway: 1,500 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUMW', 'Runway: 1,254 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUNA', 'Runway: 560 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUPA', 'Runway: 1,760 m; Unpaved', 'Wikipedia - List of airports in Uganda'),
('HUSO', 'Runways: 1,900 m and 770 m; Asphalt', 'Wikipedia - List of airports in Uganda'),
('HUTO', 'Runway: 1,707 m; Unpaved', 'Wikipedia - List of airports in Uganda')
ON DUPLICATE KEY UPDATE
  source_note = VALUES(source_note),
  data_source_name = VALUES(data_source_name);
