-- West Africa airport seed batch.
-- Rows without ICAO are intentionally skipped because airports.icao_code is the primary key.

USE icaro_ops;

INSERT INTO airports (
  icao_code,
  country_id,
  icao_prefix,
  iata_code,
  name,
  city,
  location_name,
  subdivision_name,
  latitude,
  longitude,
  elevation_ft,
  airport_type,
  service_category,
  is_civilian,
  is_commercial,
  is_military,
  is_closed,
  operator_country_name,
  aip_url,
  chart_url,
  source_rating_percent,
  data_source_name,
  data_source_url,
  data_quality
) VALUES
('GBYD', 47, 'GB', 'BJL', 'Banjul International Airport', 'Banjul', NULL, NULL, 13.3379611, -16.6522056, 95, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in The Gambia', 'https://en.wikipedia.org/wiki/List_of_airports_in_The_Gambia', 'PARTIAL'),
('DBBR', 43, 'DB', NULL, 'Bembereke Airport', 'Bembèrèkè', NULL, 'Borgou', 10.2736111, 2.6961111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBC', 43, 'DB', NULL, 'Cana Airport', 'Bohicon', NULL, 'Zou', 7.1255556, 2.0469444, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBB', 43, 'DB', 'COO', 'Cadjehoun Airport', 'Cotonou', NULL, 'Littoral', 6.3572222, 2.3844444, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBD', 43, 'DB', 'DJA', 'Djougou Airport', 'Djougou', NULL, 'Donga', 9.6919444, 1.6375, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBK', 43, 'DB', 'KDC', 'Kandi Airport', 'Kandi', NULL, 'Alibori', 11.1447222, 2.9397222, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBN', 43, 'DB', 'NAE', 'Boundétingou Airport', 'Natitingou', NULL, 'Atakora', 10.3769444, 1.3602778, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBP', 43, 'DB', 'PKO', 'Parakou Airport', 'Parakou', NULL, 'Borgou', 9.3569444, 2.6091667, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBO', 43, 'DB', NULL, 'Porga Airport', 'Porga', NULL, 'Atakora', 11.0463889, 0.9930556, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DBBS', 43, 'DB', 'SVF', 'Savé Airport', 'Savé', NULL, 'Collines', 8.0180556, 2.4644444, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Benin', 'https://en.wikipedia.org/wiki/List_of_airports_in_Benin', 'PARTIAL'),
('DFOY', 44, 'DF', 'XAR', 'Aribinda Airport', 'Aribinda', NULL, 'Soum', 14.2152778, -0.8955556, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFER', 44, 'DF', 'ARL', 'Arly Airport', 'Arly', NULL, 'Tapoa', 11.5963611, 1.4805, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOB', 44, 'DF', 'BNR', 'Banfora Airport', 'Banfora', NULL, 'Komoé', 10.6893611, -4.7275278, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCB', 44, 'DF', NULL, 'Barsalogho Airport', 'Barsalogho', NULL, 'Sanmatenga', 13.4000278, -1.0633611, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOO', 44, 'DF', 'BOY', 'Bobo Dioulasso Airport', 'Bobo Dioulasso', NULL, 'Houet', 11.1598056, -4.3312222, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEB', 44, 'DF', 'XBG', 'Bogandé Airport', 'Bogandé', NULL, 'Gnagna', 12.9813889, -0.1626111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCO', 44, 'DF', NULL, 'Boromo Airport closed', 'Boromo', NULL, 'Balé', 11.7644167, -2.9298333, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEA', 44, 'DF', 'XBO', 'Boulsa Airport', 'Boulsa', NULL, 'Namentenga', 12.6579722, -0.5687778, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOA', 44, 'DF', NULL, 'Dano Airport', 'Dano', NULL, 'Ioba', 11.1380556, -3.0743056, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOD', 44, 'DF', 'DGU', 'Dédougou Airport', 'Dédougou', NULL, 'Mouhoun', 12.4608056, -3.4885556, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFED', 44, 'DF', 'DIP', 'Diapaga Airport', 'Diapaga', NULL, 'Tapoa', 12.0604722, 1.7848889, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCD', 44, 'DF', NULL, 'Didyr Airport', 'Didyr', NULL, 'Sanguié', 12.5511667, -2.6190833, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOU', 44, 'DF', 'XDE', 'Diébougou Airport', 'Diébougou', NULL, 'Bougouriba', 10.9481667, -3.2498611, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCJ', 44, 'DF', 'XDJ', 'Djibo Airport', 'Djibo', NULL, 'Soum', 14.126, -1.6243333, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEE', 44, 'DF', 'DOR', 'Dori Airport', 'Dori', NULL, 'Séno', 14.0245278, -0.0653611, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEF', 44, 'DF', 'FNG', 'Fada N''Gourma Airport', 'Fada N''Gourma', NULL, 'Gourma', 12.0406667, 0.3643333, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOG', 44, 'DF', 'XGA', 'Gaoua Airport', 'Gaoua', NULL, 'Poni', 10.383, -3.1643889, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEG', 44, 'DF', 'XGG', 'Gorom Gorom Airport', 'Gorom Gorom', NULL, 'Oudalan', 14.4553611, -0.2176944, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOH', 44, 'DF', NULL, 'Houndé Airport', 'Houndé', NULL, 'Tuy', 11.4906111, -3.5407778, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEL', 44, 'DF', 'XKA', 'Kantchari Airport', 'Kantchari', NULL, 'Tapoa', 12.4646389, 1.4935833, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCA', 44, 'DF', 'XKY', 'Kaya Airport', 'Kaya', NULL, 'Sanmatenga', 13.0773611, -1.1002778, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCG', 44, 'DF', NULL, 'Kongoussi Airport', 'Kongoussi', NULL, 'Bam', 13.3230556, -1.5364444, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCK', 44, 'DF', NULL, 'Koudougou Airport', 'Koudougou', NULL, 'Sanguié', 12.2676389, -2.3874167, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCL', 44, 'DF', 'XLU', 'Leo Airport', 'Leo', NULL, 'Sissili', 11.1054167, -2.1016111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFON', 44, 'DF', 'XNU', 'Nouna Airport', 'Nouna', NULL, 'Kossi', 12.7435278, -3.8630278, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOR', 44, 'DF', NULL, 'Orodara Airport', 'Orodara', NULL, 'Kénédougou', 10.9868056, -4.9244722, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFFD', 44, 'DF', 'OUA', 'Thomas Sankara International Airport Ouagadougou', 'Ouagadougou', NULL, 'Kadiogo', 12.35375, -1.512, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCC', 44, 'DF', 'OUG', 'Ouahigouya Airport', 'Ouahigouya', NULL, 'Yatenga', 13.5629444, -2.4231389, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEP', 44, 'DF', 'XPA', 'Pama Airport', 'Pama', NULL, 'Kompienga', 11.2552222, 0.6982222, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCP', 44, 'DF', 'PUP', 'Pô Airport', 'Pô', NULL, 'Nahouri', 11.1791389, -1.1484722, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCR', 44, 'DF', NULL, 'Poura Airport', 'Poura', NULL, 'Balé', 11.61775, -2.7524167, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFES', 44, 'DF', 'XSE', 'Sebba Airport', 'Sebba', NULL, 'Yagha', 13.4566667, 0.5033333, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCS', 44, 'DF', NULL, 'Séguénéga Airport', 'Séguénéga', NULL, 'Yatenga', 13.4402222, -1.9929444, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEM', 44, 'DF', 'TMQ', 'Tambao Airport', 'Tambao', NULL, 'Oudalan', 14.7908333, 0.0411111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFET', 44, 'DF', 'TEG', 'Tenkodogo Airport', 'Tenkodogo', NULL, 'Boulgou', 11.8023333, -0.3715, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFOT', 44, 'DF', 'TUQ', 'Tougan Airport', 'Tougan', NULL, 'Sourou', 13.0590556, -3.07725, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFCY', 44, 'DF', NULL, 'Yako Airport Closed', 'Yako', NULL, 'Passoré', 12.9558333, -2.2744444, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('DFEZ', 44, 'DF', 'XZA', 'Zabré Airport', 'Zabré', NULL, 'Boulgou', 11.16, -0.6311111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Burkina Faso', 'https://en.wikipedia.org/wiki/List_of_airports_in_Burkina_Faso', 'PARTIAL'),
('GVBA', 45, 'GV', 'BVC', 'Aristides Pereira International Airport', 'Rabil', NULL, 'Boa Vista', 16.1363889, -22.8888889, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVSF', 45, 'GV', 'SFL', 'São Filipe Airport', 'São Filipe', NULL, 'Fogo', 14.8852778, -24.4802778, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVMA', 45, 'GV', 'MMO', 'Maio Airport', 'Porto Inglês', NULL, 'Maio', 15.1561111, -23.2136111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVAC', 45, 'GV', 'SID', 'Amílcar Cabral International Airport', 'Espargos', NULL, 'Sal', 16.7422222, -22.9488889, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVNP', 45, 'GV', 'RAI', 'Nelson Mandela International Airport', 'Praia', NULL, 'Santiago', 14.9413889, -23.4847222, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVSN', 45, 'GV', 'SNE', 'São Nicolau Airport', 'Preguiça', NULL, 'São Nicolau', 16.5883333, -24.2841667, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVSV', 45, 'GV', 'VXE', 'Cesária Évora Airport', 'São Pedro', NULL, 'São Vicente', 16.8333333, -25.0555556, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVBR', 45, 'GV', 'BVR', 'Esperadinha Airport', 'Brava', NULL, 'Brava', 14.8644444, -24.7461111, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVMT', 45, 'GV', 'MTI', 'Mosteiros Airport', 'Mosteiros', NULL, 'Fogo', 15.045, -24.34, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVFM', 45, 'GV', 'RAI', 'Francisco Mendes International Airport', 'Praia', NULL, 'Santiago', 14.924, -23.494, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('GVAN', 45, 'GV', 'NTO', 'Agostinho Neto Airport', 'Ponta do Sol', NULL, 'Santo Antão', 17.2030556, -25.0908333, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, TRUE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Cape Verde', 'https://en.wikipedia.org/wiki/List_of_airports_in_Cape_Verde', 'PARTIAL'),
('DGAA', 48, 'DG', 'ACC', 'Accra International Airport', 'Accra', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGAD', 48, 'DG', NULL, 'Ada Airstrip', 'Ada', NULL, NULL, NULL, NULL, NULL, 'AIRSTRIP', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGLB', 48, 'DG', NULL, 'Bole Airstrip', 'Bole', NULL, NULL, NULL, NULL, NULL, 'AIRSTRIP', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGAH', 48, 'DG', 'HZO', 'Ho Airport', 'Ho', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGSI', 48, 'DG', 'KMS', 'Kumasi Airport', 'Kumasi', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGSO', 48, 'DG', NULL, 'Obuasi Airport', 'Obuasi', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGLN', 48, 'DG', NULL, 'Navrongo Airport', 'Paga', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGAS', 48, 'DG', NULL, 'Saltpond Airstrip', 'Saltpond', NULL, NULL, NULL, NULL, NULL, 'AIRSTRIP', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGTK', 48, 'DG', 'TKD', 'Takoradi Airport', 'Sekondi-Takoradi', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGSN', 48, 'DG', 'NYI', 'Sunyani Airport', 'Sunyani', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGLE', 48, 'DG', 'TML', 'Tamale Airport', 'Tamale', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGLW', 48, 'DG', 'WZA', 'Wa Airport', 'Wa', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGSW', 48, 'DG', NULL, 'Wenchi Airstrip', 'Wenchi', NULL, NULL, NULL, NULL, NULL, 'AIRSTRIP', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DGLY', 48, 'DG', NULL, 'Yendi Airport', 'Yendi', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Ghana', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ghana', 'PARTIAL'),
('DIAU', 46, 'DI', 'OGO', 'Abengourou Airport', 'Abengourou', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIAP', 46, 'DI', 'ABJ', 'Port Bouët Airport (Félix Houphouët-Boigny Int''l)', 'Abidjan', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIAO', 46, 'DI', 'ABO', 'Aboisso Airport', 'Aboisso', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIBC', 46, 'DI', NULL, 'Bocanda Airport', 'Bocanda', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIBU', 46, 'DI', 'BDK', 'Soko Airport', 'Bondoukou', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIBK', 46, 'DI', 'BYK', 'Bouaké Airport', 'Bouaké', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIBN', 46, 'DI', 'BQO', 'Tehini Airport', 'Bouna', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIBI', 46, 'DI', 'BXI', 'Boundiali Airport', 'Boundiali', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIDB', 46, 'DI', NULL, 'Dabou Airport', 'Dabou', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIDL', 46, 'DI', 'DJO', 'Daloa Airport', 'Daloa', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIDK', 46, 'DI', 'DIM', 'Dimbokro Airport', 'Dimbokro', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIDV', 46, 'DI', 'DIV', 'Divo Airport', 'Divo', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIFK', 46, 'DI', 'FEK', 'Ferkessédougou Airport', 'Ferkessédougou', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIGA', 46, 'DI', 'GGN', 'Gagnoa Airport', 'Gagnoa', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIGN', 46, 'DI', 'BBV', 'Nero-Mer Airport', 'Grand-Béréby', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIGL', 46, 'DI', 'GGO', 'Guiglo Airport', 'Guiglo', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIKO', 46, 'DI', 'HGO', 'Korhogo Airport', 'Korhogo', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIMN', 46, 'DI', 'MJC', 'Man Airport', 'Man', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIOD', 46, 'DI', 'KEO', 'Odienné Airport', 'Odienné', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIOF', 46, 'DI', 'OFI', 'Ouango Fitini Airport', 'Ouango Fitini', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DISP', 46, 'DI', 'SPY', 'San Pédro Airport', 'San Pédro', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DISS', 46, 'DI', 'ZSS', 'Sassandra Airport', 'Sassandra', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DISG', 46, 'DI', 'SEO', 'Séguéla Airport', 'Séguéla', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DITB', 46, 'DI', 'TXU', 'Tabou Airport', 'Tabou', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DITM', 46, 'DI', 'TOZ', 'Mahana Airport', 'Touba', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'NATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL'),
('DIYO', 46, 'DI', 'ASK', 'Yamoussoukro International Airport', 'Yamoussoukro', NULL, NULL, NULL, NULL, NULL, 'AIRPORT', 'INTERNATIONAL', TRUE, TRUE, FALSE, FALSE, NULL, NULL, NULL, NULL, 'Wikipedia - List of airports in Côte d''Ivoire', 'https://en.wikipedia.org/wiki/List_of_airports_in_Ivory_Coast', 'PARTIAL')
ON DUPLICATE KEY UPDATE
  country_id = VALUES(country_id),
  icao_prefix = VALUES(icao_prefix),
  iata_code = VALUES(iata_code),
  name = VALUES(name),
  city = VALUES(city),
  location_name = VALUES(location_name),
  subdivision_name = VALUES(subdivision_name),
  latitude = VALUES(latitude),
  longitude = VALUES(longitude),
  elevation_ft = VALUES(elevation_ft),
  airport_type = VALUES(airport_type),
  service_category = VALUES(service_category),
  is_civilian = VALUES(is_civilian),
  is_commercial = VALUES(is_commercial),
  is_military = VALUES(is_military),
  is_closed = VALUES(is_closed),
  operator_country_name = VALUES(operator_country_name),
  aip_url = VALUES(aip_url),
  chart_url = VALUES(chart_url),
  source_rating_percent = VALUES(source_rating_percent),
  data_source_name = VALUES(data_source_name),
  data_source_url = VALUES(data_source_url),
  data_quality = VALUES(data_quality);
