-- Icaro Ops staff/personnel system.
--
-- Purpose:
--   Introduce game-generated staff candidates and hired company staff.
--
-- Design:
--   - Candidates are people generated by the game.
--   - If hired, they become persistent company staff.
--   - Pilots and technicians have personality parameters and licenses/ratings.
--   - A Cessna 208 passenger flight will require at least:
--       2 hired pilots
--       Commercial Pilot License
--       C208 type rating
--     Technical requirements will be enforced later in flight dispatch/maintenance.
--
-- Run:
--   sudo mysql icaro_ops < db/mysql/074_create_staff_personnel.sql

USE icaro_ops;

START TRANSACTION;

-- For now, focus the game on the player's own base.
-- This keeps rival company data in the DB, but hides their bases from the map
-- because api/public/map/bases.php only returns active rivals.
UPDATE rival_companies
SET is_active = FALSE
WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS staff_license_types (
  code VARCHAR(50) NOT NULL,
  name VARCHAR(120) NOT NULL,
  staff_role VARCHAR(30) NOT NULL,
  description VARCHAR(500) NOT NULL,
  is_required_for_commercial_ops BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (code),
  KEY idx_staff_license_types_role (staff_role),
  CONSTRAINT chk_staff_license_types_role
    CHECK (staff_role IN ('PILOT', 'TECHNICIAN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_candidates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  display_name VARCHAR(180) NOT NULL,

  staff_role VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',

  home_region_code VARCHAR(30) NULL,
  preferred_base_icao_code CHAR(4) NULL,

  age_years TINYINT UNSIGNED NOT NULL,
  experience_level VARCHAR(30) NOT NULL,

  fear_score TINYINT UNSIGNED NOT NULL,
  courage_score TINYINT UNSIGNED NOT NULL,
  stress_tolerance_score TINYINT UNSIGNED NOT NULL,
  discipline_score TINYINT UNSIGNED NOT NULL,
  teamwork_score TINYINT UNSIGNED NOT NULL,
  reliability_score TINYINT UNSIGNED NOT NULL,
  ambition_score TINYINT UNSIGNED NOT NULL,
  fatigue_risk_score TINYINT UNSIGNED NOT NULL,

  flight_hours_total INT UNSIGNED NOT NULL DEFAULT 0,
  aircraft_maintenance_hours_total INT UNSIGNED NOT NULL DEFAULT 0,

  salary_per_flight DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  daily_retainer DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  revenue_share_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  currency_code CHAR(3) NOT NULL DEFAULT 'EUR',

  hiring_bonus DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  morale_score TINYINT UNSIGNED NOT NULL DEFAULT 70,

  generated_at_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at_utc TIMESTAMP NULL,

  PRIMARY KEY (id),
  KEY idx_staff_candidates_role_status (staff_role, status),
  KEY idx_staff_candidates_base (preferred_base_icao_code),
  CONSTRAINT fk_staff_candidates_preferred_base
    FOREIGN KEY (preferred_base_icao_code)
    REFERENCES airports(icao_code)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT chk_staff_candidates_role
    CHECK (staff_role IN ('PILOT', 'TECHNICIAN')),

  CONSTRAINT chk_staff_candidates_status
    CHECK (status IN ('AVAILABLE', 'HIRED', 'EXPIRED', 'REJECTED')),

  CONSTRAINT chk_staff_candidates_scores
    CHECK (
      fear_score BETWEEN 0 AND 100
      AND courage_score BETWEEN 0 AND 100
      AND stress_tolerance_score BETWEEN 0 AND 100
      AND discipline_score BETWEEN 0 AND 100
      AND teamwork_score BETWEEN 0 AND 100
      AND reliability_score BETWEEN 0 AND 100
      AND ambition_score BETWEEN 0 AND 100
      AND fatigue_risk_score BETWEEN 0 AND 100
      AND morale_score BETWEEN 0 AND 100
    ),

  CONSTRAINT chk_staff_candidates_currency
    CHECK (currency_code IN ('EUR', 'USD')),

  CONSTRAINT chk_staff_candidates_compensation
    CHECK (
      salary_per_flight >= 0
      AND daily_retainer >= 0
      AND revenue_share_percent BETWEEN 0 AND 100
      AND hiring_bonus >= 0
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_candidate_licenses (
  candidate_id BIGINT UNSIGNED NOT NULL,
  license_code VARCHAR(50) NOT NULL,
  proficiency_score TINYINT UNSIGNED NOT NULL DEFAULT 70,
  issued_at_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at_utc TIMESTAMP NULL,
  PRIMARY KEY (candidate_id, license_code),
  KEY idx_staff_candidate_licenses_license (license_code),

  CONSTRAINT fk_staff_candidate_licenses_candidate
    FOREIGN KEY (candidate_id)
    REFERENCES staff_candidates(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_staff_candidate_licenses_license
    FOREIGN KEY (license_code)
    REFERENCES staff_license_types(code)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_staff_candidate_licenses_proficiency
    CHECK (proficiency_score BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_staff (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  company_id BIGINT UNSIGNED NOT NULL,
  source_candidate_id BIGINT UNSIGNED NULL,

  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  display_name VARCHAR(180) NOT NULL,

  staff_role VARCHAR(30) NOT NULL,
  employment_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

  assigned_base_icao_code CHAR(4) NOT NULL,

  age_years TINYINT UNSIGNED NOT NULL,
  experience_level VARCHAR(30) NOT NULL,

  fear_score TINYINT UNSIGNED NOT NULL,
  courage_score TINYINT UNSIGNED NOT NULL,
  stress_tolerance_score TINYINT UNSIGNED NOT NULL,
  discipline_score TINYINT UNSIGNED NOT NULL,
  teamwork_score TINYINT UNSIGNED NOT NULL,
  reliability_score TINYINT UNSIGNED NOT NULL,
  ambition_score TINYINT UNSIGNED NOT NULL,
  fatigue_risk_score TINYINT UNSIGNED NOT NULL,

  flight_hours_total INT UNSIGNED NOT NULL DEFAULT 0,
  aircraft_maintenance_hours_total INT UNSIGNED NOT NULL DEFAULT 0,

  salary_per_flight DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  daily_retainer DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  revenue_share_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  currency_code CHAR(3) NOT NULL DEFAULT 'EUR',

  morale_score TINYINT UNSIGNED NOT NULL DEFAULT 70,
  fatigue_score TINYINT UNSIGNED NOT NULL DEFAULT 0,

  hired_at_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dismissed_at_utc TIMESTAMP NULL,

  PRIMARY KEY (id),
  KEY idx_company_staff_company_role (company_id, staff_role, employment_status),
  KEY idx_company_staff_base (assigned_base_icao_code),
  KEY idx_company_staff_source_candidate (source_candidate_id),

  CONSTRAINT fk_company_staff_company
    FOREIGN KEY (company_id)
    REFERENCES companies(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_company_staff_source_candidate
    FOREIGN KEY (source_candidate_id)
    REFERENCES staff_candidates(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT fk_company_staff_base
    FOREIGN KEY (assigned_base_icao_code)
    REFERENCES airports(icao_code)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_company_staff_role
    CHECK (staff_role IN ('PILOT', 'TECHNICIAN')),

  CONSTRAINT chk_company_staff_status
    CHECK (employment_status IN ('ACTIVE', 'SUSPENDED', 'TRAINING', 'ON_LEAVE', 'DISMISSED')),

  CONSTRAINT chk_company_staff_scores
    CHECK (
      fear_score BETWEEN 0 AND 100
      AND courage_score BETWEEN 0 AND 100
      AND stress_tolerance_score BETWEEN 0 AND 100
      AND discipline_score BETWEEN 0 AND 100
      AND teamwork_score BETWEEN 0 AND 100
      AND reliability_score BETWEEN 0 AND 100
      AND ambition_score BETWEEN 0 AND 100
      AND fatigue_risk_score BETWEEN 0 AND 100
      AND morale_score BETWEEN 0 AND 100
      AND fatigue_score BETWEEN 0 AND 100
    ),

  CONSTRAINT chk_company_staff_currency
    CHECK (currency_code IN ('EUR', 'USD')),

  CONSTRAINT chk_company_staff_compensation
    CHECK (
      salary_per_flight >= 0
      AND daily_retainer >= 0
      AND revenue_share_percent BETWEEN 0 AND 100
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_staff_licenses (
  company_staff_id BIGINT UNSIGNED NOT NULL,
  license_code VARCHAR(50) NOT NULL,
  proficiency_score TINYINT UNSIGNED NOT NULL DEFAULT 70,
  issued_at_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at_utc TIMESTAMP NULL,
  PRIMARY KEY (company_staff_id, license_code),
  KEY idx_company_staff_licenses_license (license_code),

  CONSTRAINT fk_company_staff_licenses_staff
    FOREIGN KEY (company_staff_id)
    REFERENCES company_staff(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_company_staff_licenses_license
    FOREIGN KEY (license_code)
    REFERENCES staff_license_types(code)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_company_staff_licenses_proficiency
    CHECK (proficiency_score BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO staff_license_types (
  code,
  name,
  staff_role,
  description,
  is_required_for_commercial_ops
) VALUES
('PPL', 'Private Pilot License', 'PILOT', 'Basic private flying license. Not enough for commercial passenger operations.', FALSE),
('CPL', 'Commercial Pilot License', 'PILOT', 'Minimum commercial pilot license required to operate revenue passenger flights.', TRUE),
('IR', 'Instrument Rating', 'PILOT', 'Allows instrument flight operations and improves bad-weather dispatch reliability.', FALSE),
('MEP', 'Multi-engine Piston Rating', 'PILOT', 'Multi-engine piston aircraft qualification.', FALSE),
('TURBOPROP_BASIC', 'Basic Turboprop Qualification', 'PILOT', 'General turboprop experience and conversion training.', FALSE),
('C208_TYPE', 'Cessna 208 Caravan Type Familiarization', 'PILOT', 'Operational qualification for Cessna 208/208B Caravan family in this game.', TRUE),
('DHC6_TYPE', 'DHC-6 Twin Otter Type Familiarization', 'PILOT', 'Operational qualification for DHC-6 Twin Otter family.', FALSE),
('ATR42_TYPE', 'ATR 42 Type Rating', 'PILOT', 'Operational qualification for ATR 42 regional turboprop family.', FALSE),
('A_AND_P', 'Airframe and Powerplant Technician', 'TECHNICIAN', 'General aircraft maintenance authorization.', TRUE),
('TURBOPROP_MAINT', 'Turboprop Maintenance Qualification', 'TECHNICIAN', 'Maintenance qualification for turboprop aircraft.', TRUE),
('AVIONICS_BASIC', 'Basic Avionics Technician', 'TECHNICIAN', 'Basic avionics and onboard systems maintenance skill.', FALSE),
('C208_MAINT', 'Cessna 208 Maintenance Qualification', 'TECHNICIAN', 'Specific maintenance qualification for Cessna 208/208B Caravan family.', TRUE)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  staff_role = VALUES(staff_role),
  description = VALUES(description),
  is_required_for_commercial_ops = VALUES(is_required_for_commercial_ops),
  is_active = TRUE;

-- Seed initial job market candidates. These are generated fictional people.
INSERT INTO staff_candidates (
  first_name,
  last_name,
  display_name,
  staff_role,
  status,
  home_region_code,
  preferred_base_icao_code,
  age_years,
  experience_level,
  fear_score,
  courage_score,
  stress_tolerance_score,
  discipline_score,
  teamwork_score,
  reliability_score,
  ambition_score,
  fatigue_risk_score,
  flight_hours_total,
  aircraft_maintenance_hours_total,
  salary_per_flight,
  daily_retainer,
  revenue_share_percent,
  currency_code,
  hiring_bonus,
  morale_score
) VALUES
('Marco', 'Bellucci', 'Marco Bellucci', 'PILOT', 'AVAILABLE', 'EUROPE', 'LIRA', 34, 'REGIONAL_EXPERIENCED', 22, 78, 74, 82, 70, 86, 61, 18, 1850, 0, 520.00, 80.00, 1.50, 'EUR', 2500.00, 74),
('Elena', 'Conti', 'Elena Conti', 'PILOT', 'AVAILABLE', 'EUROPE', 'LIRA', 29, 'COMMERCIAL_JUNIOR', 31, 69, 67, 76, 85, 79, 72, 23, 920, 0, 410.00, 65.00, 1.00, 'EUR', 1800.00, 78),
('Nadia', 'Ferri', 'Nadia Ferri', 'PILOT', 'AVAILABLE', 'EUROPE', 'LIRA', 41, 'SENIOR_TURBOPROP', 18, 84, 81, 88, 66, 91, 44, 16, 4200, 0, 760.00, 120.00, 2.00, 'EUR', 4200.00, 69),
('Tommaso', 'Rinaldi', 'Tommaso Rinaldi', 'PILOT', 'AVAILABLE', 'EUROPE', 'LIRA', 26, 'LOW_HOURS_COMMERCIAL', 42, 62, 58, 70, 73, 68, 88, 32, 430, 0, 320.00, 40.00, 0.50, 'EUR', 1000.00, 81),
('Sara', 'Marini', 'Sara Marini', 'TECHNICIAN', 'AVAILABLE', 'EUROPE', 'LIRA', 37, 'TURBOPROP_TECH', 12, 72, 78, 89, 77, 84, 50, 20, 0, 6900, 0.00, 140.00, 0.00, 'EUR', 2600.00, 76),
('Giulio', 'Serra', 'Giulio Serra', 'TECHNICIAN', 'AVAILABLE', 'EUROPE', 'LIRA', 31, 'AVIONICS_TECH', 24, 65, 71, 83, 80, 77, 63, 25, 0, 3400, 0.00, 115.00, 0.00, 'EUR', 1800.00, 73),
('Irene', 'Dalmasso', 'Irene Dalmasso', 'TECHNICIAN', 'AVAILABLE', 'EUROPE', 'LIRA', 45, 'SENIOR_A_AND_P', 10, 77, 84, 92, 71, 89, 38, 14, 0, 9800, 0.00, 180.00, 0.00, 'EUR', 3800.00, 68)
ON DUPLICATE KEY UPDATE
  status = staff_candidates.status;

-- Candidate licenses.
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'CPL', 82 FROM staff_candidates WHERE display_name = 'Marco Bellucci';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'IR', 78 FROM staff_candidates WHERE display_name = 'Marco Bellucci';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'TURBOPROP_BASIC', 76 FROM staff_candidates WHERE display_name = 'Marco Bellucci';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'C208_TYPE', 80 FROM staff_candidates WHERE display_name = 'Marco Bellucci';

INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'CPL', 74 FROM staff_candidates WHERE display_name = 'Elena Conti';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'IR', 70 FROM staff_candidates WHERE display_name = 'Elena Conti';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'C208_TYPE', 72 FROM staff_candidates WHERE display_name = 'Elena Conti';

INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'CPL', 91 FROM staff_candidates WHERE display_name = 'Nadia Ferri';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'IR', 86 FROM staff_candidates WHERE display_name = 'Nadia Ferri';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'TURBOPROP_BASIC', 92 FROM staff_candidates WHERE display_name = 'Nadia Ferri';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'C208_TYPE', 88 FROM staff_candidates WHERE display_name = 'Nadia Ferri';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'DHC6_TYPE', 75 FROM staff_candidates WHERE display_name = 'Nadia Ferri';

INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'CPL', 66 FROM staff_candidates WHERE display_name = 'Tommaso Rinaldi';

INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'A_AND_P', 88 FROM staff_candidates WHERE display_name = 'Sara Marini';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'TURBOPROP_MAINT', 82 FROM staff_candidates WHERE display_name = 'Sara Marini';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'C208_MAINT', 84 FROM staff_candidates WHERE display_name = 'Sara Marini';

INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'A_AND_P', 76 FROM staff_candidates WHERE display_name = 'Giulio Serra';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'AVIONICS_BASIC', 85 FROM staff_candidates WHERE display_name = 'Giulio Serra';

INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'A_AND_P', 93 FROM staff_candidates WHERE display_name = 'Irene Dalmasso';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'TURBOPROP_MAINT', 89 FROM staff_candidates WHERE display_name = 'Irene Dalmasso';
INSERT IGNORE INTO staff_candidate_licenses (candidate_id, license_code, proficiency_score)
SELECT id, 'C208_MAINT', 91 FROM staff_candidates WHERE display_name = 'Irene Dalmasso';

CREATE OR REPLACE VIEW v_staff_candidates_available AS
SELECT
  c.id AS candidate_id,
  c.first_name,
  c.last_name,
  c.display_name,
  c.staff_role,
  c.status,
  c.home_region_code,
  c.preferred_base_icao_code,
  c.age_years,
  c.experience_level,
  c.fear_score,
  c.courage_score,
  c.stress_tolerance_score,
  c.discipline_score,
  c.teamwork_score,
  c.reliability_score,
  c.ambition_score,
  c.fatigue_risk_score,
  c.flight_hours_total,
  c.aircraft_maintenance_hours_total,
  c.salary_per_flight,
  c.daily_retainer,
  c.revenue_share_percent,
  c.currency_code,
  c.hiring_bonus,
  c.morale_score,
  GROUP_CONCAT(CONCAT(l.code, ':', scl.proficiency_score) ORDER BY l.code SEPARATOR ', ') AS licenses_summary
FROM staff_candidates c
LEFT JOIN staff_candidate_licenses scl
  ON scl.candidate_id = c.id
LEFT JOIN staff_license_types l
  ON l.code = scl.license_code
WHERE c.status = 'AVAILABLE'
GROUP BY
  c.id,
  c.first_name,
  c.last_name,
  c.display_name,
  c.staff_role,
  c.status,
  c.home_region_code,
  c.preferred_base_icao_code,
  c.age_years,
  c.experience_level,
  c.fear_score,
  c.courage_score,
  c.stress_tolerance_score,
  c.discipline_score,
  c.teamwork_score,
  c.reliability_score,
  c.ambition_score,
  c.fatigue_risk_score,
  c.flight_hours_total,
  c.aircraft_maintenance_hours_total,
  c.salary_per_flight,
  c.daily_retainer,
  c.revenue_share_percent,
  c.currency_code,
  c.hiring_bonus,
  c.morale_score;

CREATE OR REPLACE VIEW v_company_staff AS
SELECT
  s.id AS company_staff_id,
  s.company_id,
  co.company_name,
  s.first_name,
  s.last_name,
  s.display_name,
  s.staff_role,
  s.employment_status,
  s.assigned_base_icao_code,
  s.age_years,
  s.experience_level,
  s.fear_score,
  s.courage_score,
  s.stress_tolerance_score,
  s.discipline_score,
  s.teamwork_score,
  s.reliability_score,
  s.ambition_score,
  s.fatigue_risk_score,
  s.flight_hours_total,
  s.aircraft_maintenance_hours_total,
  s.salary_per_flight,
  s.daily_retainer,
  s.revenue_share_percent,
  s.currency_code,
  s.morale_score,
  s.fatigue_score,
  GROUP_CONCAT(CONCAT(l.code, ':', csl.proficiency_score) ORDER BY l.code SEPARATOR ', ') AS licenses_summary
FROM company_staff s
JOIN companies co
  ON co.id = s.company_id
LEFT JOIN company_staff_licenses csl
  ON csl.company_staff_id = s.id
LEFT JOIN staff_license_types l
  ON l.code = csl.license_code
GROUP BY
  s.id,
  s.company_id,
  co.company_name,
  s.first_name,
  s.last_name,
  s.display_name,
  s.staff_role,
  s.employment_status,
  s.assigned_base_icao_code,
  s.age_years,
  s.experience_level,
  s.fear_score,
  s.courage_score,
  s.stress_tolerance_score,
  s.discipline_score,
  s.teamwork_score,
  s.reliability_score,
  s.ambition_score,
  s.fatigue_risk_score,
  s.flight_hours_total,
  s.aircraft_maintenance_hours_total,
  s.salary_per_flight,
  s.daily_retainer,
  s.revenue_share_percent,
  s.currency_code,
  s.morale_score,
  s.fatigue_score;

SELECT staff_role, COUNT(*) AS available_candidates
FROM staff_candidates
WHERE status = 'AVAILABLE'
GROUP BY staff_role;

COMMIT;
