-- Icaro Ops - clean aircraft catalog display names and deduplicate obvious duplicate models
-- Generated from aircraft_models_review.tsv provided during catalog cleanup.
-- Scope: display fields only (manufacturer/model_name) plus is_active for obvious generic/duplicate rows.
START TRANSACTION;

UPDATE aircraft_models SET manufacturer = 'AC11', model_name = 'COMMANDER 114', is_active = 1 WHERE id = 88;
UPDATE aircraft_models SET manufacturer = 'Aero', model_name = 'Commander 500', is_active = 1 WHERE id = 89;
UPDATE aircraft_models SET manufacturer = 'AeroAndina', model_name = 'MXP-1000 Tayrona', is_active = 1 WHERE id = 254;
UPDATE aircraft_models SET manufacturer = 'Aerospatiale', model_name = 'Se.210 Caravelle', is_active = 1 WHERE id = 159;
UPDATE aircraft_models SET manufacturer = 'ATR', model_name = 'ATR42-300/320', is_active = 1 WHERE id = 101;
UPDATE aircraft_models SET manufacturer = 'ATR', model_name = 'ATR42-500', is_active = 1 WHERE id = 102;
UPDATE aircraft_models SET manufacturer = 'ATR', model_name = 'ATR72', is_active = 1 WHERE id = 103;
UPDATE aircraft_models SET manufacturer = 'Aerospatiale/BAC', model_name = 'Concorde', is_active = 0 WHERE id = 285;
UPDATE aircraft_models SET manufacturer = 'Aerospatiale/BAC', model_name = 'Concorde', is_active = 1 WHERE id = 9;
UPDATE aircraft_models SET manufacturer = 'Agusta', model_name = 'A109', is_active = 1 WHERE id = 77;
UPDATE aircraft_models SET manufacturer = 'AgustaWestland', model_name = 'AW609 Tiltrotor', is_active = 1 WHERE id = 293;
UPDATE aircraft_models SET manufacturer = 'AgustaWestland', model_name = 'AW139', is_active = 1 WHERE id = 82;
UPDATE aircraft_models SET manufacturer = 'AgustaWestland', model_name = 'EH101 / AW101', is_active = 1 WHERE id = 205;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A310-200', is_active = 1 WHERE id = 16;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A310-300', is_active = 1 WHERE id = 17;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A319neo', is_active = 1 WHERE id = 21;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A321neo', is_active = 1 WHERE id = 25;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A400M Atlas', is_active = 1 WHERE id = 40;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A220-100', is_active = 1 WHERE id = 14;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A220-300', is_active = 1 WHERE id = 15;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A300-600', is_active = 1 WHERE id = 87;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A318', is_active = 1 WHERE id = 18;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A318 Business Jet', is_active = 1 WHERE id = 20;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A319', is_active = 1 WHERE id = 19;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A320neo', is_active = 1 WHERE id = 24;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A330-200', is_active = 1 WHERE id = 26;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A330-300', is_active = 1 WHERE id = 27;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A330-800 neo', is_active = 1 WHERE id = 29;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A330-900 neo', is_active = 1 WHERE id = 30;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A340-200', is_active = 1 WHERE id = 31;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A340-300', is_active = 1 WHERE id = 32;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A340-500', is_active = 1 WHERE id = 33;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A340-600', is_active = 1 WHERE id = 34;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A350-1000', is_active = 1 WHERE id = 35;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A350-900', is_active = 1 WHERE id = 36;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A380', is_active = 1 WHERE id = 39;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A380', is_active = 1 WHERE id = 38;
UPDATE aircraft_models SET manufacturer = 'Airbus Helicopters', model_name = 'H135', is_active = 1 WHERE id = 224;
UPDATE aircraft_models SET manufacturer = 'Airbus Helicopters', model_name = 'H145', is_active = 1 WHERE id = 225;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A320-100/200', is_active = 1 WHERE id = 22;
UPDATE aircraft_models SET manufacturer = 'Airbus', model_name = 'A321-100/200', is_active = 1 WHERE id = 23;
UPDATE aircraft_models SET manufacturer = 'Aircraft Industries', model_name = 'L 410 NG', is_active = 1 WHERE id = 5;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-12', is_active = 1 WHERE id = 97;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-124 Ruslan', is_active = 1 WHERE id = 85;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-140', is_active = 1 WHERE id = 83;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-140', is_active = 1 WHERE id = 84;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-24', is_active = 1 WHERE id = 94;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-26', is_active = 1 WHERE id = 78;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-30', is_active = 1 WHERE id = 80;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-32', is_active = 1 WHERE id = 81;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-30 / AN-32', is_active = 1 WHERE id = 95;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'PZL Miele M-28 Skytruck', is_active = 1 WHERE id = 79;
UPDATE aircraft_models SET manufacturer = 'Antonov', model_name = 'AN-74', is_active = 1 WHERE id = 96;
UPDATE aircraft_models SET manufacturer = 'ATR', model_name = '42-600', is_active = 1 WHERE id = 7;
UPDATE aircraft_models SET manufacturer = 'Austflight', model_name = 'drifter', is_active = 1 WHERE id = 194;
UPDATE aircraft_models SET manufacturer = 'Aviat', model_name = 'Pitts Special S2S', is_active = 1 WHERE id = 273;
UPDATE aircraft_models SET manufacturer = 'Avro', model_name = 'RJ100 Avroliner', is_active = 1 WHERE id = 98;
UPDATE aircraft_models SET manufacturer = 'Avro', model_name = 'RJ85 Avroliner', is_active = 1 WHERE id = 99;
UPDATE aircraft_models SET manufacturer = 'Avro', model_name = 'RJX100', is_active = 1 WHERE id = 104;
UPDATE aircraft_models SET manufacturer = 'Avro', model_name = 'RJX85', is_active = 1 WHERE id = 105;
UPDATE aircraft_models SET manufacturer = 'Avro', model_name = '85/100 Avroliner', is_active = 1 WHERE id = 100;
UPDATE aircraft_models SET manufacturer = 'Ayres', model_name = 'LM-200 Loadmaster', is_active = 1 WHERE id = 93;
UPDATE aircraft_models SET manufacturer = 'BAC', model_name = '1-11 (One-Eleven)', is_active = 1 WHERE id = 108;
UPDATE aircraft_models SET manufacturer = 'BAe', model_name = '146-100', is_active = 1 WHERE id = 11;
UPDATE aircraft_models SET manufacturer = 'BAe', model_name = '146-200', is_active = 1 WHERE id = 12;
UPDATE aircraft_models SET manufacturer = 'BAe', model_name = '146-300', is_active = 1 WHERE id = 13;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'Baron G58', is_active = 1 WHERE id = 119;
UPDATE aircraft_models SET manufacturer = 'Beech', model_name = 'Bonanza A36', is_active = 1 WHERE id = 111;
UPDATE aircraft_models SET manufacturer = 'Beech', model_name = 'Bonanza F33A', is_active = 1 WHERE id = 122;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'H35', is_active = 1 WHERE id = 110;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = '1900D', is_active = 1 WHERE id = 121;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'Bonanza G36', is_active = 1 WHERE id = 117;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'Duke 60', is_active = 1 WHERE id = 114;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'King Air 350i', is_active = 1 WHERE id = 118;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'Model 99', is_active = 1 WHERE id = 120;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'Super King Air B200', is_active = 1 WHERE id = 109;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'Turbine Duke', is_active = 1 WHERE id = 107;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = '1900C/1900D', is_active = 1 WHERE id = 115;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'Baron 58', is_active = 1 WHERE id = 116;
UPDATE aircraft_models SET manufacturer = 'Beechcraft', model_name = 'King Air 350', is_active = 1 WHERE id = 123;
UPDATE aircraft_models SET manufacturer = 'Bell', model_name = '206', is_active = 1 WHERE id = 106;
UPDATE aircraft_models SET manufacturer = 'Bell', model_name = '407', is_active = 1 WHERE id = 113;
UPDATE aircraft_models SET manufacturer = 'Bell', model_name = '412 All Models', is_active = 1 WHERE id = 112;
UPDATE aircraft_models SET manufacturer = 'Bell', model_name = 'Helicopter family', is_active = 0 WHERE id = 124;
UPDATE aircraft_models SET manufacturer = 'Bellanca', model_name = 'Scout - Super Decathlon', is_active = 1 WHERE id = 125;
UPDATE aircraft_models SET manufacturer = 'Beriev', model_name = 'Be-200c', is_active = 1 WHERE id = 127;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '377 Stratocruiser', is_active = 1 WHERE id = 37;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '707-300', is_active = 1 WHERE id = 43;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '717-200', is_active = 1 WHERE id = 44;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '727-200', is_active = 1 WHERE id = 45;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737 MAX 10', is_active = 1 WHERE id = 76;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737 MAX 7', is_active = 1 WHERE id = 73;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737 MAX 8', is_active = 1 WHERE id = 74;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737 MAX 9', is_active = 1 WHERE id = 75;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-100', is_active = 1 WHERE id = 46;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-200', is_active = 1 WHERE id = 47;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-300', is_active = 1 WHERE id = 48;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-400', is_active = 1 WHERE id = 49;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-500', is_active = 1 WHERE id = 50;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-600', is_active = 1 WHERE id = 51;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-700 (winglets)', is_active = 1 WHERE id = 57;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-700', is_active = 1 WHERE id = 54;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-800 (winglets)', is_active = 1 WHERE id = 55;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-800', is_active = 1 WHERE id = 52;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-900 (winglets)', is_active = 1 WHERE id = 56;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '737-900', is_active = 1 WHERE id = 53;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '747-100', is_active = 1 WHERE id = 58;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '747-200', is_active = 1 WHERE id = 59;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '747-300', is_active = 1 WHERE id = 60;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '747-400', is_active = 1 WHERE id = 61;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '747-8i', is_active = 1 WHERE id = 62;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '757-200', is_active = 1 WHERE id = 63;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '757-300', is_active = 1 WHERE id = 64;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '767-200', is_active = 1 WHERE id = 65;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '767-300', is_active = 1 WHERE id = 66;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '767-400', is_active = 1 WHERE id = 67;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '777-200', is_active = 1 WHERE id = 68;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '777-300', is_active = 1 WHERE id = 69;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '787-10 Dreamliner', is_active = 1 WHERE id = 70;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '787-8 Dreamliner', is_active = 1 WHERE id = 71;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = '787-9 Dreamliner', is_active = 1 WHERE id = 72;
UPDATE aircraft_models SET manufacturer = 'Boeing', model_name = 'C-17 Globemaster III', is_active = 1 WHERE id = 130;
UPDATE aircraft_models SET manufacturer = 'Bombardier', model_name = 'C-Series CS100', is_active = 1 WHERE id = 161;
UPDATE aircraft_models SET manufacturer = 'Bombardier', model_name = 'C-Series CS300', is_active = 1 WHERE id = 162;
UPDATE aircraft_models SET manufacturer = 'British Aerospace', model_name = 'Jetstream 31', is_active = 1 WHERE id = 230;
UPDATE aircraft_models SET manufacturer = 'British Aerospace', model_name = 'Jetstream 32', is_active = 1 WHERE id = 231;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Challenger', is_active = 1 WHERE id = 138;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'CL-44', is_active = 1 WHERE id = 143;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Global Express', is_active = 1 WHERE id = 139;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Regional Jet 100', is_active = 1 WHERE id = 154;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Regional Jet 1000', is_active = 1 WHERE id = 160;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Regional Jet 200', is_active = 1 WHERE id = 155;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Regional Jet 550', is_active = 1 WHERE id = 156;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Regional Jet 700', is_active = 1 WHERE id = 157;
UPDATE aircraft_models SET manufacturer = 'Canadair', model_name = 'Regional Jet 900', is_active = 1 WHERE id = 158;
UPDATE aircraft_models SET manufacturer = 'Caproni', model_name = 'VIZZOLA C-22J Ventura', is_active = 1 WHERE id = 133;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '172 Skyhawk', is_active = 1 WHERE id = 136;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '208 B Grand Caravan EX', is_active = 1 WHERE id = 146;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '208 Caravan', is_active = 1 WHERE id = 153;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '310R', is_active = 1 WHERE id = 134;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '337 Super Skymaster', is_active = 1 WHERE id = 28;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '414AW Chancellor', is_active = 1 WHERE id = 42;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '441 Conquest', is_active = 1 WHERE id = 150;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'C510 Mustang', is_active = 1 WHERE id = 135;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'Citation family', is_active = 0 WHERE id = 151;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'Citation CJ3', is_active = 1 WHERE id = 147;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'Citation CJ4', is_active = 1 WHERE id = 148;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'Citation Longitude', is_active = 1 WHERE id = 149;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'CT182T Skylane', is_active = 1 WHERE id = 137;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'Single-engine piston aircraft', is_active = 0 WHERE id = 144;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'Twin-engine piston aircraft', is_active = 0 WHERE id = 145;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = 'Twin-engine turboprop aircraft', is_active = 0 WHERE id = 152;
UPDATE aircraft_models SET manufacturer = 'Cessna', model_name = '152 Aerobat', is_active = 1 WHERE id = 129;
UPDATE aircraft_models SET manufacturer = 'Cirrus', model_name = 'SR 20', is_active = 1 WHERE id = 131;
UPDATE aircraft_models SET manufacturer = 'Cirrus', model_name = 'SR 22', is_active = 1 WHERE id = 132;
UPDATE aircraft_models SET manufacturer = 'Cirrus', model_name = 'Vision SF50', is_active = 1 WHERE id = 283;
UPDATE aircraft_models SET manufacturer = 'Claudius', model_name = 'Dornier CD-2 Seastar', is_active = 1 WHERE id = 140;
UPDATE aircraft_models SET manufacturer = 'Convair', model_name = 'CV-440 Metropolitan', is_active = 1 WHERE id = 165;
UPDATE aircraft_models SET manufacturer = 'Convair', model_name = '440 / 580 / 600 / 640', is_active = 1 WHERE id = 166;
UPDATE aircraft_models SET manufacturer = 'Cub', model_name = 'Crafter X Cub', is_active = 1 WHERE id = 164;
UPDATE aircraft_models SET manufacturer = 'DA20', model_name = 'Katana', is_active = 1 WHERE id = 177;
UPDATE aircraft_models SET manufacturer = 'Daher', model_name = 'TBM 930', is_active = 1 WHERE id = 292;
UPDATE aircraft_models SET manufacturer = 'Dassault', model_name = 'Falcon 50', is_active = 1 WHERE id = 186;
UPDATE aircraft_models SET manufacturer = 'Dassault', model_name = 'Falcon 50 / Falcon M', is_active = 1 WHERE id = 188;
UPDATE aircraft_models SET manufacturer = 'De Havilland Canada', model_name = 'DHC-2 Beaver', is_active = 1 WHERE id = 192;
UPDATE aircraft_models SET manufacturer = 'De Havilland Canada', model_name = 'DHC-3 Turbo Otter', is_active = 1 WHERE id = 191;
UPDATE aircraft_models SET manufacturer = 'De Havilland Canada', model_name = 'DHC-6 Twin Otter', is_active = 1 WHERE id = 193;
UPDATE aircraft_models SET manufacturer = 'De Havilland Canada', model_name = 'DHC-8-300', is_active = 1 WHERE id = 189;
UPDATE aircraft_models SET manufacturer = 'De Havilland Canada', model_name = 'DHC-8-400', is_active = 1 WHERE id = 190;
UPDATE aircraft_models SET manufacturer = 'De Havilland Canada', model_name = 'DHC-6 Twin Otter Series 400', is_active = 1 WHERE id = 4;
UPDATE aircraft_models SET manufacturer = 'Diamond', model_name = 'DA42 Twin Star', is_active = 1 WHERE id = 179;
UPDATE aircraft_models SET manufacturer = 'Diamond', model_name = 'DA62', is_active = 1 WHERE id = 180;
UPDATE aircraft_models SET manufacturer = 'Diamond', model_name = 'DV20', is_active = 1 WHERE id = 195;
UPDATE aircraft_models SET manufacturer = 'Diamond', model_name = 'DA40 TDI/NG', is_active = 1 WHERE id = 178;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-4', is_active = 1 WHERE id = 182;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-6', is_active = 1 WHERE id = 183;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-7', is_active = 1 WHERE id = 184;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-8-50', is_active = 1 WHERE id = 185;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-9-10', is_active = 1 WHERE id = 172;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-9-20', is_active = 1 WHERE id = 173;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-9-30', is_active = 1 WHERE id = 174;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-9-40', is_active = 1 WHERE id = 175;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-9-50', is_active = 1 WHERE id = 176;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-10', is_active = 1 WHERE id = 167;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = 'DC-3', is_active = 1 WHERE id = 181;
UPDATE aircraft_models SET manufacturer = 'Douglas', model_name = '40 Freighters', is_active = 1 WHERE id = 168;
UPDATE aircraft_models SET manufacturer = 'Eclipse Aerospace', model_name = 'Eclipse 550', is_active = 1 WHERE id = 204;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = 'EMB 120ER Brasilia', is_active = 1 WHERE id = 8;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '110', is_active = 1 WHERE id = 206;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '120', is_active = 1 WHERE id = 207;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '170', is_active = 1 WHERE id = 200;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '175', is_active = 1 WHERE id = 201;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '190', is_active = 1 WHERE id = 202;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '195', is_active = 1 WHERE id = 203;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '500 - Phenom 100', is_active = 1 WHERE id = 208;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = '505 Phenom 300', is_active = 1 WHERE id = 209;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = 'RJ135', is_active = 1 WHERE id = 210;
UPDATE aircraft_models SET manufacturer = 'Embraer', model_name = 'RJ145 Amazon', is_active = 1 WHERE id = 211;
UPDATE aircraft_models SET manufacturer = 'Enstrom', model_name = '280', is_active = 1 WHERE id = 197;
UPDATE aircraft_models SET manufacturer = 'Eurocopter', model_name = 'AS350', is_active = 1 WHERE id = 278;
UPDATE aircraft_models SET manufacturer = 'Eurocopter', model_name = 'BK117', is_active = 1 WHERE id = 233;
UPDATE aircraft_models SET manufacturer = 'Eurocopter', model_name = 'EC120', is_active = 1 WHERE id = 196;
UPDATE aircraft_models SET manufacturer = 'Eurocopter', model_name = 'EC135', is_active = 1 WHERE id = 199;
UPDATE aircraft_models SET manufacturer = 'Extra Aircraft', model_name = 'EA-300 / EA-330 / EA-350', is_active = 1 WHERE id = 198;
UPDATE aircraft_models SET manufacturer = 'Fairchild Dornier', model_name = '328JET', is_active = 1 WHERE id = 218;
UPDATE aircraft_models SET manufacturer = 'Fairchild Dornier', model_name = '328', is_active = 1 WHERE id = 170;
UPDATE aircraft_models SET manufacturer = 'Dassault', model_name = 'Falcon 7X', is_active = 1 WHERE id = 187;
UPDATE aircraft_models SET manufacturer = 'Flight', model_name = 'Design CTSL', is_active = 1 WHERE id = 163;
UPDATE aircraft_models SET manufacturer = 'Fokker', model_name = '100', is_active = 1 WHERE id = 10;
UPDATE aircraft_models SET manufacturer = 'Fokker', model_name = '27 Friendship', is_active = 1 WHERE id = 213;
UPDATE aircraft_models SET manufacturer = 'Fokker', model_name = '50', is_active = 1 WHERE id = 215;
UPDATE aircraft_models SET manufacturer = 'Fokker', model_name = '70', is_active = 1 WHERE id = 216;
UPDATE aircraft_models SET manufacturer = 'Fokker', model_name = 'F.28 Fellowship', is_active = 1 WHERE id = 214;
UPDATE aircraft_models SET manufacturer = 'FSR', model_name = '500', is_active = 1 WHERE id = 219;
UPDATE aircraft_models SET manufacturer = 'Gates', model_name = 'Learjet', is_active = 1 WHERE id = 240;
UPDATE aircraft_models SET manufacturer = 'Goodyear', model_name = 'GZ-20', is_active = 1 WHERE id = 220;
UPDATE aircraft_models SET manufacturer = 'Grumman', model_name = 'C-2 Greyhound', is_active = 1 WHERE id = 222;
UPDATE aircraft_models SET manufacturer = 'Grumman', model_name = 'Goose - Amphibious', is_active = 1 WHERE id = 223;
UPDATE aircraft_models SET manufacturer = 'Guimbal', model_name = 'Cabri G2', is_active = 1 WHERE id = 221;
UPDATE aircraft_models SET manufacturer = 'Gulfstream', model_name = 'Rockwell Commander', is_active = 1 WHERE id = 91;
UPDATE aircraft_models SET manufacturer = 'Gulfstream', model_name = 'Rockwell Commander/Turbo Commander', is_active = 1 WHERE id = 90;
UPDATE aircraft_models SET manufacturer = 'Gulfstream', model_name = 'Rockwell Turbo Commander', is_active = 1 WHERE id = 92;
UPDATE aircraft_models SET manufacturer = 'Hawker', model_name = 'Hurricane MK-1', is_active = 1 WHERE id = 251;
UPDATE aircraft_models SET manufacturer = 'Hawker', model_name = 'Sideley 748', is_active = 1 WHERE id = 227;
UPDATE aircraft_models SET manufacturer = 'Honda Aircraft', model_name = 'HA-420 HondaJet', is_active = 1 WHERE id = 226;
UPDATE aircraft_models SET manufacturer = 'ICON Aircraft', model_name = 'A5', is_active = 1 WHERE id = 86;
UPDATE aircraft_models SET manufacturer = 'ICP', model_name = 'Savannah', is_active = 1 WHERE id = 286;
UPDATE aircraft_models SET manufacturer = 'Ilyushin', model_name = 'IL-18', is_active = 1 WHERE id = 228;
UPDATE aircraft_models SET manufacturer = 'Ilyushin', model_name = 'IL96', is_active = 1 WHERE id = 229;
UPDATE aircraft_models SET manufacturer = 'British Aerospace', model_name = 'Jetstream 41', is_active = 1 WHERE id = 232;
UPDATE aircraft_models SET manufacturer = 'JMB', model_name = 'Aircraft VL-3', is_active = 1 WHERE id = 296;
UPDATE aircraft_models SET manufacturer = 'Kitfox', model_name = 'STi FreedomFox & Fox2', is_active = 1 WHERE id = 217;
UPDATE aircraft_models SET manufacturer = 'Kodiak', model_name = '100', is_active = 1 WHERE id = 234;
UPDATE aircraft_models SET manufacturer = 'Lancair', model_name = 'Legacy', is_active = 1 WHERE id = 237;
UPDATE aircraft_models SET manufacturer = 'Lockheed', model_name = 'L-1011 Tristar', is_active = 1 WHERE id = 235;
UPDATE aircraft_models SET manufacturer = 'Lockheed', model_name = 'L-1049 Super Constellation', is_active = 1 WHERE id = 236;
UPDATE aircraft_models SET manufacturer = 'Lockheed', model_name = 'L188 Electra', is_active = 1 WHERE id = 238;
UPDATE aircraft_models SET manufacturer = 'Lockheed', model_name = 'Hercules C130', is_active = 1 WHERE id = 239;
UPDATE aircraft_models SET manufacturer = 'Martin', model_name = '404', is_active = 1 WHERE id = 41;
UPDATE aircraft_models SET manufacturer = 'Maule', model_name = '7-235, MT-7, MX-7-260', is_active = 1 WHERE id = 243;
UPDATE aircraft_models SET manufacturer = 'Maule', model_name = '7-420, MX-7-420, MXT-7', is_active = 1 WHERE id = 244;
UPDATE aircraft_models SET manufacturer = 'McDonnell Douglas', model_name = 'MD-11', is_active = 1 WHERE id = 241;
UPDATE aircraft_models SET manufacturer = 'McDonnell Douglas', model_name = 'MD-80', is_active = 1 WHERE id = 245;
UPDATE aircraft_models SET manufacturer = 'McDonnell Douglas', model_name = 'MD-81', is_active = 1 WHERE id = 246;
UPDATE aircraft_models SET manufacturer = 'McDonnell Douglas', model_name = 'MD-82', is_active = 1 WHERE id = 247;
UPDATE aircraft_models SET manufacturer = 'McDonnell Douglas', model_name = 'MD-83', is_active = 1 WHERE id = 248;
UPDATE aircraft_models SET manufacturer = 'McDonnell Douglas', model_name = 'MD-87', is_active = 1 WHERE id = 249;
UPDATE aircraft_models SET manufacturer = 'McDonnell Douglas', model_name = 'MD-88', is_active = 1 WHERE id = 250;
UPDATE aircraft_models SET manufacturer = 'Mitsubishi', model_name = 'Marquise All Models', is_active = 1 WHERE id = 253;
UPDATE aircraft_models SET manufacturer = 'Mooney', model_name = 'Bravo - M20R Ovation', is_active = 1 WHERE id = 242;
UPDATE aircraft_models SET manufacturer = 'De Havilland', model_name = 'Mosquito', is_active = 1 WHERE id = 252;
UPDATE aircraft_models SET manufacturer = 'North American', model_name = 'P-51D Mustang', is_active = 1 WHERE id = 260;
UPDATE aircraft_models SET manufacturer = 'NAMC', model_name = 'YS-11', is_active = 1 WHERE id = 301;
UPDATE aircraft_models SET manufacturer = 'PAC', model_name = 'P-750XSTOL - PAC 750XL', is_active = 1 WHERE id = 261;
UPDATE aircraft_models SET manufacturer = 'Piaggio', model_name = 'P-180 Avanti', is_active = 1 WHERE id = 258;
UPDATE aircraft_models SET manufacturer = 'Piaggio', model_name = 'P.149', is_active = 1 WHERE id = 257;
UPDATE aircraft_models SET manufacturer = 'Pilatus', model_name = 'PC-12 Eagle', is_active = 1 WHERE id = 256;
UPDATE aircraft_models SET manufacturer = 'Pilatus', model_name = 'PC-24', is_active = 1 WHERE id = 259;
UPDATE aircraft_models SET manufacturer = 'Pilatus', model_name = 'PC-6 Turbo Porter', is_active = 1 WHERE id = 272;
UPDATE aircraft_models SET manufacturer = 'Pilatus Aircraft', model_name = 'PC-12 NGX', is_active = 1 WHERE id = 2;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'Single-engine piston aircraft', is_active = 0 WHERE id = 263;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'Twin-engine piston aircraft', is_active = 0 WHERE id = 264;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'Malibu Mirage', is_active = 1 WHERE id = 269;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'PA-24 Comanche', is_active = 1 WHERE id = 267;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'PA-44 Seminole', is_active = 1 WHERE id = 266;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'PA28R ARROW III', is_active = 1 WHERE id = 268;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'PA34 Seneca', is_active = 1 WHERE id = 265;
UPDATE aircraft_models SET manufacturer = 'Piper', model_name = 'Piper Cheyenne II', is_active = 1 WHERE id = 270;
UPDATE aircraft_models SET manufacturer = 'Pipistrel', model_name = 'Virus SW 121', is_active = 1 WHERE id = 271;
UPDATE aircraft_models SET manufacturer = 'Robin', model_name = 'DR-300', is_active = 1 WHERE id = 169;
UPDATE aircraft_models SET manufacturer = 'Robin', model_name = '100 Cadet - CAP 10', is_active = 1 WHERE id = 171;
UPDATE aircraft_models SET manufacturer = 'Robinson', model_name = 'R22', is_active = 1 WHERE id = 274;
UPDATE aircraft_models SET manufacturer = 'Rutan', model_name = 'Boomerang M202', is_active = 1 WHERE id = 126;
UPDATE aircraft_models SET manufacturer = 'Saab', model_name = '340B', is_active = 1 WHERE id = 6;
UPDATE aircraft_models SET manufacturer = 'Saab', model_name = '2000', is_active = 1 WHERE id = 277;
UPDATE aircraft_models SET manufacturer = 'Saab', model_name = '340A/B', is_active = 1 WHERE id = 281;
UPDATE aircraft_models SET manufacturer = 'Schweizer', model_name = '2-32', is_active = 1 WHERE id = 280;
UPDATE aircraft_models SET manufacturer = 'SIAI-Marchetti', model_name = 'S-205', is_active = 1 WHERE id = 276;
UPDATE aircraft_models SET manufacturer = 'SIAI-Marchetti', model_name = 'SF-260', is_active = 1 WHERE id = 212;
UPDATE aircraft_models SET manufacturer = 'Socata', model_name = 'TB21GT Trinidad', is_active = 1 WHERE id = 289;
UPDATE aircraft_models SET manufacturer = 'Socata', model_name = 'TBM 700', is_active = 1 WHERE id = 290;
UPDATE aircraft_models SET manufacturer = 'Socata', model_name = 'TBM-850 Turboprop', is_active = 1 WHERE id = 291;
UPDATE aircraft_models SET manufacturer = 'Sting', model_name = 'S4 Ultralight', is_active = 1 WHERE id = 284;
UPDATE aircraft_models SET manufacturer = 'Tecnam', model_name = 'P-2002 Sierra', is_active = 1 WHERE id = 282;
UPDATE aircraft_models SET manufacturer = 'Tecnam', model_name = 'P-2004 Bravo', is_active = 1 WHERE id = 128;
UPDATE aircraft_models SET manufacturer = 'Tecnam', model_name = 'P2006', is_active = 1 WHERE id = 255;
UPDATE aircraft_models SET manufacturer = 'Tecnam', model_name = 'P92', is_active = 1 WHERE id = 262;
UPDATE aircraft_models SET manufacturer = 'Textron Aviation / Beechcraft', model_name = 'King Air 360', is_active = 1 WHERE id = 3;
UPDATE aircraft_models SET manufacturer = 'Textron Aviation / Cessna', model_name = '208B Grand Caravan EX', is_active = 1 WHERE id = 1;
UPDATE aircraft_models SET manufacturer = 'Tupolev', model_name = 'TU-114 Rossiya', is_active = 1 WHERE id = 287;
UPDATE aircraft_models SET manufacturer = 'Tupolev', model_name = 'TU154', is_active = 1 WHERE id = 294;
UPDATE aircraft_models SET manufacturer = 'Tupolev', model_name = 'Tu-214', is_active = 1 WHERE id = 288;
UPDATE aircraft_models SET manufacturer = 'Van''s Aircraft', model_name = 'RV-14 / RV-14A', is_active = 1 WHERE id = 275;
UPDATE aircraft_models SET manufacturer = 'Vickers', model_name = 'Viscount', is_active = 1 WHERE id = 295;
UPDATE aircraft_models SET manufacturer = 'Viking', model_name = 'Air 415 (Canadair CL-415)', is_active = 1 WHERE id = 142;
UPDATE aircraft_models SET manufacturer = 'Vought', model_name = 'Corsair F4U', is_active = 1 WHERE id = 298;
UPDATE aircraft_models SET manufacturer = 'Waco', model_name = '(Vintage 1929)', is_active = 1 WHERE id = 297;
UPDATE aircraft_models SET manufacturer = 'XtremeAir', model_name = 'XA-42 Sbach 342', is_active = 1 WHERE id = 299;
UPDATE aircraft_models SET manufacturer = 'Yakovlev', model_name = 'Yak 40', is_active = 1 WHERE id = 300;
UPDATE aircraft_models SET manufacturer = 'Zenith', model_name = 'STOL CH801', is_active = 1 WHERE id = 141;
UPDATE aircraft_models SET manufacturer = 'Zlin Aviation', model_name = 'Savage Cub / Shock Ultra', is_active = 1 WHERE id = 279;

-- Keep the curated Concorde entry visible and hide the imported duplicate that represents the same aircraft.
UPDATE aircraft_models SET is_active = 1 WHERE id = 9;
UPDATE aircraft_models SET is_active = 0 WHERE id = 285;

COMMIT;