#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path.cwd()
FLEET_HTML = ROOT / "fleet.html"
FLEET_JS = ROOT / "src/js/fleet.js"
FLEET_CSS = ROOT / "src/css/fleet.css"


def replace_function(source: str, name: str, replacement: str) -> str:
    marker = f"function {name}"
    start = source.find(marker)
    if start < 0:
        marker = f"async function {name}"
        start = source.find(marker)
    if start < 0:
        raise SystemExit(f"Could not find function {name}()")

    brace = source.find("{", start)
    if brace < 0:
        raise SystemExit(f"Could not find opening brace for {name}()")

    depth = 0
    i = brace
    in_string = None
    escaped = False
    template_depth = 0
    # Lightweight scanner good enough for this codebase.
    while i < len(source):
        ch = source[i]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == in_string:
                in_string = None
        else:
            if ch in ('"', "'", "`"):
                in_string = ch
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    return source[:start] + replacement.rstrip() + "\n\n" + source[i+1:]
        i += 1

    raise SystemExit(f"Could not find closing brace for {name}()")


def insert_after_once(source: str, needle: str, insertion: str) -> str:
    if insertion.strip() in source:
        return source
    idx = source.find(needle)
    if idx < 0:
        raise SystemExit(f"Could not find insertion point: {needle!r}")
    idx += len(needle)
    return source[:idx] + insertion + source[idx:]


def patch_html():
    text = FLEET_HTML.read_text()

    # Replace the owned fleet header with a compact version if the old text is still there.
    text = re.sub(
        r'''<div class="card-header">\s*<div>\s*<h2>Owned aircraft</h2>\s*<p>Essential data only\. Open details for technical and financial information\.</p>\s*</div>\s*<button id="refreshButton" type="button">Refresh</button>\s*</div>''',
        '''<div class="card-header">
            <button id="refreshButton" type="button">Refresh</button>
          </div>''',
        text,
        flags=re.S,
    )

    # Replace main fleet table header only. Buy aircraft tables are generated by JS and are not touched here.
    header_pattern = r'''<thead>\s*<tr>\s*<th>Registration</th>.*?</tr>\s*</thead>'''
    header_replacement = '''<thead>
                <tr>
                  <th data-fleet-sort="registration_code">Registration</th>
                  <th data-fleet-sort="aircraft_name">Aircraft</th>
                  <th data-fleet-sort="status_display">Status</th>
                  <th data-fleet-sort="condition_percent" data-sort-type="number">Condition</th>
                  <th data-fleet-sort="airframe_hours" data-sort-type="number">Hours</th>
                  <th data-fleet-sort="cycles_count" data-sort-type="number">Cycles</th>
                </tr>
              </thead>'''
    text, count = re.subn(header_pattern, header_replacement, text, count=1, flags=re.S)
    if count == 0:
        raise SystemExit("Could not replace Fleet table header")

    # Loading colspans: Fleet table now has 6 columns.
    text = text.replace('<tr><td colspan="8">Loading...</td></tr>', '<tr><td colspan="6">Loading...</td></tr>')
    text = text.replace('<tr><td colspan="7">Loading...</td></tr>', '<tr><td colspan="6">Loading...</td></tr>')

    FLEET_HTML.write_text(text)


def patch_js():
    text = FLEET_JS.read_text()

    # Add sort state after ownedAircraft declaration.
    if "let fleetSortState" not in text:
        text = text.replace(
            "let ownedAircraft = [];\nlet catalogAircraft = [];",
            "let ownedAircraft = [];\nlet catalogAircraft = [];\nlet fleetSortState = { key: null, direction: \"asc\" };"
        )

    # Add sorting initializer in DOMContentLoaded.
    if "setupFleetTableSorting();" not in text:
        text = text.replace(
            "document.querySelector(\"#buyAircraftButton\")?.addEventListener(\"click\", openBuyDialog);\n  await loadFleet();",
            "document.querySelector(\"#buyAircraftButton\")?.addEventListener(\"click\", openBuyDialog);\n  setupFleetTableSorting();\n  await loadFleet();"
        )

    render_fleet_table = r'''function renderFleetTable(rows) {
  const tbody = document.querySelector("#fleetTableBody");
  const displayRows = sortedFleetRows(rows);

  if (!displayRows.length) {
    tbody.innerHTML = `<tr><td colspan="6">No owned aircraft yet.</td></tr>`;
    return;
  }

  tbody.innerHTML = displayRows.map(a => {
    const aircraftName = `${a.manufacturer || ""} ${a.model_name || ""}`.trim() || "Aircraft";

    return `
      <tr>
        <td><strong>${escapeHtml(a.registration_code)}</strong></td>
        <td>
          <button type="button" class="aircraft-name-link" data-aircraft-detail="${escapeHtml(a.aircraft_id)}">
            ${escapeHtml(aircraftName)}
          </button>
        </td>
        <td><span class="badge fleet-status-badge ${statusClass(a.status)}">${escapeHtml(displayAircraftStatus(a))}</span></td>
        <td class="${conditionClass(a.condition_percent)}">${escapeHtml(a.condition_percent ?? "-")}%</td>
        <td>${escapeHtml(a.airframe_hours ?? "0")}</td>
        <td>${escapeHtml(a.cycles_count ?? "0")}</td>
      </tr>
    `;
  }).join("");

  tbody.querySelectorAll("[data-aircraft-detail]").forEach(button => {
    button.addEventListener("click", () => openAircraftDetailFromButton(button));
  });
}'''
    text = replace_function(text, "renderFleetTable", render_fleet_table)

    open_detail = r'''async function openAircraftDetail(aircraftId) {
  const dialog = document.querySelector("#aircraftDetailDialog");
  const title = document.querySelector("#aircraftDetailTitle");
  const content = document.querySelector("#aircraftDetailContent");

  title.textContent = "Aircraft";
  content.textContent = "Loading...";
  setAircraftDetailFooter(aircraftId);
  dialog.showModal();

  try {
    const data = await getJson(API.detail(aircraftId));
    const a = data.aircraft;
    title.textContent = `${a.registration_code} · ${a.manufacturer} ${a.model_name}`;
    setAircraftDetailFooter(a.aircraft_id || aircraftId);
    content.innerHTML = renderAircraftDetail(a, data.recent_flights || []);
  } catch (error) {
    resetAircraftDetailFooter();
    content.innerHTML = `<div class="page-error">${escapeHtml(error.message || "Unable to load aircraft detail.")}</div>`;
  }
}'''
    text = replace_function(text, "openAircraftDetail", open_detail)

    # Ensure model detail dialog does not inherit owned-aircraft footer actions.
    if "resetAircraftDetailFooter();\n  title.textContent = \"Aircraft model\";" not in text:
        text = text.replace(
            "  title.textContent = \"Aircraft model\";\n  content.textContent = \"Loading...\";",
            "  resetAircraftDetailFooter();\n  title.textContent = \"Aircraft model\";\n  content.textContent = \"Loading...\";"
        )

    helper_block = r'''
function setupFleetTableSorting() {
  const table = document.querySelector("#fleetTableBody")?.closest("table");
  if (!table) return;

  table.querySelectorAll("thead th[data-fleet-sort]").forEach(header => {
    const key = header.dataset.fleetSort;
    header.classList.add("sortable-header");
    header.tabIndex = 0;
    header.title = "Sort table";

    const toggle = () => {
      if (fleetSortState.key === key) {
        fleetSortState.direction = fleetSortState.direction === "asc" ? "desc" : "asc";
      } else {
        fleetSortState.key = key;
        fleetSortState.direction = "asc";
      }

      updateFleetSortHeaders();
      renderFleetTable(ownedAircraft);
    };

    header.addEventListener("click", toggle);
    header.addEventListener("keydown", event => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        toggle();
      }
    });
  });
}

function updateFleetSortHeaders() {
  document.querySelectorAll("#fleetTableBody")
    .forEach(tbody => tbody.closest("table")?.querySelectorAll("thead th[data-fleet-sort]")
      .forEach(header => {
        header.classList.remove("sort-asc", "sort-desc");
        header.removeAttribute("aria-sort");

        if (header.dataset.fleetSort === fleetSortState.key) {
          const isAsc = fleetSortState.direction === "asc";
          header.classList.add(isAsc ? "sort-asc" : "sort-desc");
          header.setAttribute("aria-sort", isAsc ? "ascending" : "descending");
        }
      }));
}

function sortedFleetRows(rows) {
  if (!fleetSortState.key) {
    // Initial order is the backend order: first purchased to last purchased.
    return [...rows];
  }

  const direction = fleetSortState.direction === "desc" ? -1 : 1;
  const key = fleetSortState.key;

  return [...rows].sort((a, b) => direction * compareFleetValues(fleetSortValue(a, key), fleetSortValue(b, key)));
}

function fleetSortValue(row, key) {
  if (key === "aircraft_name") {
    return `${row.manufacturer || ""} ${row.model_name || ""}`.trim();
  }

  if (key === "status_display") {
    return displayAircraftStatus(row);
  }

  if (key === "condition_percent" || key === "airframe_hours" || key === "cycles_count") {
    const value = Number(row[key]);
    return Number.isFinite(value) ? value : -1;
  }

  return row[key] ?? "";
}

function compareFleetValues(left, right) {
  if (typeof left === "number" && typeof right === "number") {
    return left - right;
  }

  return String(left ?? "").localeCompare(String(right ?? ""), undefined, {
    numeric: true,
    sensitivity: "base"
  });
}

function displayAircraftStatus(a) {
  const status = String(a.status || a.aircraft_status || "").toUpperCase();

  if (status === "IN_FLIGHT") {
    return "IN FLIGHT";
  }

  const label = status || "UNKNOWN";
  const airport = currentAircraftLocationCode(a);

  return airport && airport !== "-" ? `${label} (${airport})` : label;
}

function currentAircraftLocationCode(a) {
  return a.current_airport_icao_code ||
    a.current_airport ||
    a.current_airport_code ||
    a.home_base_icao_code ||
    "-";
}

function setAircraftDetailFooter(aircraftId) {
  const footer = document.querySelector("#aircraftDetailDialog .dialog-footer");
  if (!footer) return;

  footer.innerHTML = `
    <div class="dialog-footer-actions">
      <button type="button" class="secondary" data-aircraft-image-footer="${escapeHtml(aircraftId)}">Image</button>
      <button type="button" class="secondary" data-aircraft-maintenance-footer="${escapeHtml(aircraftId)}">Maintenance</button>
    </div>
    <button value="close">Close</button>
  `;

  footer.querySelector("[data-aircraft-image-footer]")?.addEventListener("click", event => {
    openAircraftImage(Number(event.currentTarget.dataset.aircraftImageFooter));
  });

  footer.querySelector("[data-aircraft-maintenance-footer]")?.addEventListener("click", event => {
    const id = Number(event.currentTarget.dataset.aircraftMaintenanceFooter);
    if (Number.isInteger(id) && id > 0) {
      window.location.href = `maintenance.html?aircraftId=${encodeURIComponent(id)}`;
    }
  });
}

function resetAircraftDetailFooter() {
  const footer = document.querySelector("#aircraftDetailDialog .dialog-footer");
  if (!footer) return;
  footer.innerHTML = `<button value="close">Close</button>`;
}
'''

    # Insert helpers before openAircraftDetail, after renderFleetTable.
    if "function setupFleetTableSorting()" not in text:
        marker = "async function openAircraftDetail"
        idx = text.find(marker)
        if idx < 0:
            raise SystemExit("Could not insert Fleet sorting/detail footer helpers")
        text = text[:idx] + helper_block + "\n" + text[idx:]

    # Remove old airport helper if still present? Keep harmless for other references.

    FLEET_JS.write_text(text)


def patch_css():
    css = FLEET_CSS.read_text()
    append = r'''

/* Fleet table sorting and compact actions. */
.sortable-header {
  cursor: pointer;
  user-select: none;
  position: relative;
}

.sortable-header::after {
  content: "↕";
  margin-left: 6px;
  opacity: .45;
  font-size: .75rem;
}

.sortable-header.sort-asc::after {
  content: "↑";
  opacity: .95;
}

.sortable-header.sort-desc::after {
  content: "↓";
  opacity: .95;
}

.aircraft-name-link {
  padding: 0;
  border: 0;
  background: transparent;
  color: var(--accent);
  text-decoration: underline;
  text-underline-offset: 3px;
  font: inherit;
  font-weight: 800;
  cursor: pointer;
}

.aircraft-name-link:hover,
.aircraft-name-link:focus-visible {
  color: var(--text);
  background: transparent;
  outline: none;
}

.fleet-status-badge,
#fleetTableBody .badge {
  width: 100%;
  min-width: 100%;
  box-sizing: border-box;
}

.dialog-footer-actions {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  margin-right: auto;
}
'''
    if "/* Fleet table sorting and compact actions. */" not in css:
        css += append
    FLEET_CSS.write_text(css)


def main():
    if not FLEET_HTML.exists() or not FLEET_JS.exists() or not FLEET_CSS.exists():
        raise SystemExit("Run this script from the icaro-ops project root")

    patch_html()
    patch_js()
    patch_css()
    print("Patched Fleet table sorting, aircraft-name details and detail footer actions.")


if __name__ == "__main__":
    main()
